// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:26 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Fournisseur } from '../fournisseur.model';

@Injectable()
export class FournisseurService extends RestService<Fournisseur>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Fournisseur, 'fournisseur', injector);
    }

}
