// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:22 )


import { Resource } from 'angular4-hal';

export class Cra extends Resource {
	craid: number; // Wrapper Type : Number
	idconsultant: number; // Wrapper Type : Number
	codeperiode: string; // Wrapper Type : String
	commentaire: string; // Wrapper Type : String
	statut: string; // Wrapper Type : String
	datevalidation: Date; // Wrapper Type : Date
}
