// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:32 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Fraiskmunit } from '../fraiskmunit.model';

@Injectable()
export class FraiskmunitService extends RestService<Fraiskmunit>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Fraiskmunit, 'fraiskmunit', injector);
    }

}
