// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:34 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';
import { Router } from '@angular/router';
import { ActivatedRoute  } from '@angular/router';
import { MatDialog } from '@angular/material';

// Services imports
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { LiencontratService } from './../services/liencontrat.service';
import { ApplicationStateService } from './../../../services/application-state.service';

// Models imports
import { Liencontrat } from '../liencontrat.model';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Ajout primeng
import {TableModule} from 'primeng/table';
import {PaginatorModule} from 'primeng/paginator';

@Component({
  selector: 'app-liencontrat-list',
  templateUrl: './liencontrat-list.component.html',
  styleUrls: ['./liencontrat-list.component.css'],
  providers: [DatePipe]
})
export class LiencontratListComponent implements OnInit, OnChanges {

  public title = 'Liste de Liencontrats';

  public listOfLiencontrats: Liencontrat[];


  _filter : string;
  @Input('filter') 
  set filter(value:string) {
	 this._filter = value;
     this.getAllLiencontrats();
  }

  get filter():string {
	return this._filter
  }

  @Input() createenable?: boolean = true;
  @Input() deleteenable?: boolean = true;
  @Input() updateenable?: boolean = true;
  @Input() incard?: boolean = true;

  private listId = 'LIENCONTRAT_COMPONENT_LIST';

  private liencontrat: Liencontrat;

  private columnDefinitions = [
      { def: 'idcontratclient', showMobile: true, display:'table-cell', index:0},
      { def: 'idconsultantclient', showMobile: true, display:'table-cell', index:1},
      { def: 'idcontratfournisseur', showMobile: true, display:'table-cell', index:2},
      { def: 'idconsultantfournisseur', showMobile: true, display:'table-cell', index:3},
	];

  constructor(
    private _liencontratService: LiencontratService,
    private _router: Router,
    private _notificationService: NotificationService,
    public dialog: MatDialog,
	private _route: ActivatedRoute) { }

  ngOnInit() {
    // On init get all Liencontrats
    //this.getAllLiencontrats();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Liencontrat list
    EmitterService.get(this.listId).subscribe((data: Liencontrat[]) => this.getAllLiencontrats());
  }

  ngOnChanges() { }


  /**
   * Get displayed columns (responsive)
   */
  getDisplayedColumns(): string[] {
	  const isMobile = ApplicationStateService.getIsMobileResolution();
	  return this.columnDefinitions
	    .filter(cd => !isMobile || cd.showMobile)
	    .map(cd => cd.def);
	}

  /**
   * Get all Liencontrat using the service LiencontratService
   */
  getAllLiencontrats = (): void => {

	var options:any = { notPaged: true };
	
	if (this.filter) {
		if (this.filter == 'FULL') {
			options = { notPaged: true };
		}
		else {
			var filters = JSON.parse(this.filter);
			options = {params: filters,
						   notPaged: true};
		}

    	this._liencontratService.getAll(options).subscribe(
      		(data: Liencontrat[]) => {
        		this.listOfLiencontrats = data;
      		},
      	error => {
        	this._notificationService.error(
          	'Error',
          	'An error occured when trying to reach the server');
    	});
	}
  }

  editLiencontrat = (idcontratclient, idconsultantclient, idcontratfournisseur, idconsultantfournisseur): void => {
    // Navigate to liencontrat form component
    this.goToLiencontratForm(idcontratclient, idconsultantclient, idcontratfournisseur, idconsultantfournisseur);
  }

  deleteLiencontrat = (idcontratclient, idconsultantclient, idcontratfournisseur, idconsultantfournisseur): void => {

    const promise = new Promise((resolve, reject) => {
		// Call get service
		this._liencontratService.get([idcontratclient, idconsultantclient, idcontratfournisseur, idconsultantfournisseur]).subscribe(
        		(liencontrat: Liencontrat) => {
          							this.liencontrat = liencontrat;
          							resolve('done');
        						},
				error => {
          					this._notificationService.error(error.statusText, 'Error delete');
            				reject('error');
        				 });
	})
    .then(() => {
    	// Call delete service
    	this._liencontratService.delete(this.liencontrat).subscribe(
      			result => {
       						 // Notify Liencontrat list to refresh
        					EmitterService.get(this.listId).emit(result);

        					this._notificationService.success(
          					'Deleted',
          					`The liencontrat entry with the id='${idcontratclient}, ${idconsultantclient}, ${idcontratfournisseur}, ${idconsultantfournisseur}' was deleted successfuly`);
     					  },
      			error => {
        					this._notificationService.error(
          					'Error',
          					'An error occured when trying to reach the server');
      					  });
  	})
  }

  goToLiencontratForm(idcontratclient, idconsultantclient, idcontratfournisseur, idconsultantfournisseur) {
    this._router.navigate(['./liencontrat-form', idcontratclient, idconsultantclient, idcontratfournisseur, idconsultantfournisseur]);
  }

  deleteConfirmation = (idcontratclient, idconsultantclient, idcontratfournisseur, idconsultantfournisseur) => {
    const dialogRef = this.dialog.open(DeleteDialogComponent, {
      data: `liencontrat: ${idcontratclient}, ${idconsultantclient}, ${idcontratfournisseur}, ${idconsultantfournisseur}`
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteLiencontrat(idcontratclient, idconsultantclient, idcontratfournisseur, idconsultantfournisseur);
      }
    });
  }

}
