// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:35 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-liencontrat-listheader',
  templateUrl: './liencontrat-listheader.component.html',
  styleUrls: ['./liencontrat-listheader.component.css'],
  providers: []
})
export class LiencontratListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Liencontrats';
  public filter:string = 'FULL';

  private columnDefinitions = [
      { def: 'idcontratclient', showMobile: true },
      { def: 'idconsultantclient', showMobile: true },
      { def: 'idcontratfournisseur', showMobile: true },
      { def: 'idconsultantfournisseur', showMobile: true },
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
