// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:36 )


import { Resource } from 'angular4-hal';

export class Valocontrat extends Resource {
	valocontratid: number; // Wrapper Type : Number
	idcontrat: number; // Wrapper Type : Number
	profilcst: string; // Wrapper Type : String
	libelle: string; // Wrapper Type : String
	nbj: number; // Wrapper Type : Number
	taux: number; // Wrapper Type : Number
}
