// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:25 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';
import { Router } from '@angular/router';
import { ActivatedRoute  } from '@angular/router';
import { MatDialog } from '@angular/material';

// Services imports
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { ConsultantcontratfournisseurService } from './../services/consultantcontratfournisseur.service';
import { ApplicationStateService } from './../../../services/application-state.service';

// Models imports
import { Consultantcontratfournisseur } from '../consultantcontratfournisseur.model';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Ajout primeng
import {TableModule} from 'primeng/table';
import {PaginatorModule} from 'primeng/paginator';

@Component({
  selector: 'app-consultantcontratfournisseur-list',
  templateUrl: './consultantcontratfournisseur-list.component.html',
  styleUrls: ['./consultantcontratfournisseur-list.component.css'],
  providers: [DatePipe]
})
export class ConsultantcontratfournisseurListComponent implements OnInit, OnChanges {

  public title = 'Liste de Consultantcontratfournisseurs';

  public listOfConsultantcontratfournisseurs: Consultantcontratfournisseur[];


  _filter : string;
  @Input('filter') 
  set filter(value:string) {
	 this._filter = value;
     this.getAllConsultantcontratfournisseurs();
  }

  get filter():string {
	return this._filter
  }

  @Input() createenable?: boolean = true;
  @Input() deleteenable?: boolean = true;
  @Input() updateenable?: boolean = true;
  @Input() incard?: boolean = true;

  private listId = 'CONSULTANTCONTRATFOURNISSEUR_COMPONENT_LIST';

  private consultantcontratfournisseur: Consultantcontratfournisseur;

  private columnDefinitions = [
      { def: 'taux', showMobile: true, display:'none', index:0},
      { def: 'nbjprev', showMobile: true, display:'none', index:1},
      { def: 'profilcst', showMobile: true, display:'none', index:2},
      { def: 'idconsultant', showMobile: true, display:'table-cell', index:3},
      { def: 'idcontratfournisseur', showMobile: true, display:'table-cell', index:4},
      { def: 'datedebut', showMobile: true, display:'table-cell', index:5},
      { def: 'datefin', showMobile: true, display:'table-cell', index:6},
	];

  constructor(
    private _consultantcontratfournisseurService: ConsultantcontratfournisseurService,
    private _router: Router,
    private _notificationService: NotificationService,
    public dialog: MatDialog,
	private _route: ActivatedRoute) { }

  ngOnInit() {
    // On init get all Consultantcontratfournisseurs
    //this.getAllConsultantcontratfournisseurs();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Consultantcontratfournisseur list
    EmitterService.get(this.listId).subscribe((data: Consultantcontratfournisseur[]) => this.getAllConsultantcontratfournisseurs());
  }

  ngOnChanges() { }


  /**
   * Get displayed columns (responsive)
   */
  getDisplayedColumns(): string[] {
	  const isMobile = ApplicationStateService.getIsMobileResolution();
	  return this.columnDefinitions
	    .filter(cd => !isMobile || cd.showMobile)
	    .map(cd => cd.def);
	}

  /**
   * Get all Consultantcontratfournisseur using the service ConsultantcontratfournisseurService
   */
  getAllConsultantcontratfournisseurs = (): void => {

	var options:any = { notPaged: true };
	
	if (this.filter) {
		if (this.filter == 'FULL') {
			options = { notPaged: true };
		}
		else {
			var filters = JSON.parse(this.filter);
			options = {params: filters,
						   notPaged: true};
		}

    	this._consultantcontratfournisseurService.getAll(options).subscribe(
      		(data: Consultantcontratfournisseur[]) => {
        		this.listOfConsultantcontratfournisseurs = data;
      		},
      	error => {
        	this._notificationService.error(
          	'Error',
          	'An error occured when trying to reach the server');
    	});
	}
  }

  editConsultantcontratfournisseur = (idconsultant, idcontratfournisseur): void => {
    // Navigate to consultantcontratfournisseur form component
    this.goToConsultantcontratfournisseurForm(idconsultant, idcontratfournisseur);
  }

  deleteConsultantcontratfournisseur = (idconsultant, idcontratfournisseur): void => {

    const promise = new Promise((resolve, reject) => {
		// Call get service
		this._consultantcontratfournisseurService.get([idconsultant, idcontratfournisseur]).subscribe(
        		(consultantcontratfournisseur: Consultantcontratfournisseur) => {
          							this.consultantcontratfournisseur = consultantcontratfournisseur;
          							resolve('done');
        						},
				error => {
          					this._notificationService.error(error.statusText, 'Error delete');
            				reject('error');
        				 });
	})
    .then(() => {
    	// Call delete service
    	this._consultantcontratfournisseurService.delete(this.consultantcontratfournisseur).subscribe(
      			result => {
       						 // Notify Consultantcontratfournisseur list to refresh
        					EmitterService.get(this.listId).emit(result);

        					this._notificationService.success(
          					'Deleted',
          					`The consultantcontratfournisseur entry with the id='${idconsultant}, ${idcontratfournisseur}' was deleted successfuly`);
     					  },
      			error => {
        					this._notificationService.error(
          					'Error',
          					'An error occured when trying to reach the server');
      					  });
  	})
  }

  goToConsultantcontratfournisseurForm(idconsultant, idcontratfournisseur) {
    this._router.navigate(['./consultantcontratfournisseur-form', idconsultant, idcontratfournisseur]);
  }

  deleteConfirmation = (idconsultant, idcontratfournisseur) => {
    const dialogRef = this.dialog.open(DeleteDialogComponent, {
      data: `consultantcontratfournisseur: ${idconsultant}, ${idcontratfournisseur}`
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteConsultantcontratfournisseur(idconsultant, idcontratfournisseur);
      }
    });
  }

}
