// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:25 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-consultantcontratfournisseur-listheader',
  templateUrl: './consultantcontratfournisseur-listheader.component.html',
  styleUrls: ['./consultantcontratfournisseur-listheader.component.css'],
  providers: []
})
export class ConsultantcontratfournisseurListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Consultantcontratfournisseurs';
  public filter:string = 'FULL';

  private columnDefinitions = [
      { def: 'idconsultant', showMobile: true },
      { def: 'idcontratfournisseur', showMobile: true },
      { def: 'datedebut', showMobile: true },
      { def: 'datefin', showMobile: true },
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
