// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:45 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Valocontrat } from '../valocontrat.model';

@Injectable()
export class ValocontratService extends RestService<Valocontrat>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Valocontrat, 'valocontrat', injector);
    }

}
