// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:35 )


import { Resource } from 'angular4-hal';

export class Rubriquefrais extends Resource {
	code: string; // Wrapper Type : String
	nom: string; // Wrapper Type : String
	ordre: string; // Wrapper Type : String
	ccstructure: string; // Wrapper Type : String
	cccommercial: string; // Wrapper Type : String
	ccoperationnel: string; // Wrapper Type : String
	ccrefact: string; // Wrapper Type : String
	image: string; // Wrapper Type : String
}
