// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:26 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Contratfournisseur } from '../contratfournisseur.model';

@Injectable()
export class ContratfournisseurService extends RestService<Contratfournisseur>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Contratfournisseur, 'contratfournisseur', injector);
    }

}
