// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:29 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-fraisunit-listheader',
  templateUrl: './fraisunit-listheader.component.html',
  styleUrls: ['./fraisunit-listheader.component.css'],
  providers: []
})
export class FraisunitListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Fraisunits';
  public filter:string = 'FULL';

  private columnDefinitions = [
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
