// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 16:11:39 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-fraisunit-listheader',
  templateUrl: './fraisunit-listheader.component.html',
  styleUrls: ['./fraisunit-listheader.component.css'],
  providers: []
})
export class FraisunitListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Fraisunits';
  public filter:string = 'FULL';

  private columnDefinitions = [
      { def: 'fraisunitid', showMobile: true },
      { def: 'idconsultant', showMobile: true },
      { def: 'codeperiode', showMobile: true },
      { def: 'datecalendrier', showMobile: true },
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
