// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:33 )

// Modules imports
import { NotificationService } from './../../../services/notification.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material';
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Models and services imports
import { Fraisunit } from './../fraisunit.model';
import { FraisunitService } from './../services/fraisunit.service';
import * as _ from 'underscore';

// Pour gestion des listes
import { ListeService } from './../../../entities/liste/services/liste.service';
import { Liste } from './../../../entities/liste/liste.model';

import { Lov } from './../../../common/lov';
import {SelectItem} from 'primeng/api';

@Component({
  selector: 'app-fraisunit-form',
  templateUrl: './fraisunit-form.component.html',
  styleUrls: ['./fraisunit-form.component.css'],
  providers: [DatePipe]
})
export class FraisunitFormComponent extends Lov implements OnInit {

  // HTTP status code
  readonly NOT_FOUND_ERROR = 404;
  readonly CONFLICT_ERROR = 409;
  readonly INTERNAL_SERVER_ERROR = 500;

  public title = 'Formulaire Fraisunit';
  public form: FormGroup;

  // Définition des filtres

  public fraisunit: Fraisunit;
  private ids;

  // Définition des LOV

  constructor(
	private _listeService: ListeService,         // Pour gestion des listes
    private _fraisunitService: FraisunitService,
    private _route: ActivatedRoute,
    private _router: Router,
    private _formBuilder: FormBuilder,
    private _notificationService: NotificationService,
    public dialog: MatDialog) {
		super(_listeService,_notificationService);
 	}

  ngOnInit() {
    this.getIdFromRouteParams();
    this.initForm();
  }

  getIdFromRouteParams = () => {
    this._route.params.subscribe(p => {
        this.ids = _.values(p);
    });
  }

  initForm = () => {
    this.form = this._formBuilder.group(this.getNewForm());
    if (!_.isEmpty(this.ids)) {
      this.load();
    }

	/* Chargement des LOVs */
  }

  getNewForm = (fraisunit?: Fraisunit) => {
    return {
      fraisunitid: [{
          value: (fraisunit ? fraisunit.fraisunitid : ''),
          disabled: true
      }],      idconsultant: [
        (fraisunit ? fraisunit.idconsultant : ''),
        Validators.required
      ],
      codeperiode: [
        (fraisunit ? fraisunit.codeperiode : '')
      ],
      codetypefrais: [
        (fraisunit ? fraisunit.codetypefrais : '')
      ],
      datecalendrier: [
        (fraisunit ? fraisunit.datecalendrier : null)
      ],
      idcontrat: [
        (fraisunit ? fraisunit.idcontrat : ''),
        Validators.required
      ],
      montantht: [
        (fraisunit ? fraisunit.montantht : '')
      ],
      tva1: [
        (fraisunit ? fraisunit.tva1 : '')
      ],
      tva2: [
        (fraisunit ? fraisunit.tva2 : '')
      ],
      tva3: [
        (fraisunit ? fraisunit.tva3 : '')
      ],
      recu: [
        (fraisunit ? fraisunit.recu : ''),
        Validators.required
      ],
      commentaire: [
        (fraisunit ? fraisunit.commentaire : '')
      ],
      refact: [
        (fraisunit ? fraisunit.refact : ''),
        Validators.required
      ]
    };
  }


  load = () => {
	// Concaténer les ids mais séparé par / et non ,
	var param : String = '';
	
	for (var i=0;i<this.ids.length;i++) {
		param = param + this.ids[i];
		if (i != (this.ids.length-1)) {
			param = param + '/';
		}
	}
    this._fraisunitService.get(param).subscribe(
      (fraisunit: Fraisunit) => {
        this.fraisunit = fraisunit;
        this.form = this._formBuilder.group(this.getNewForm(this.fraisunit));
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
 	  },
      () => {
		// Valorisation des filtres
      });
  }

  save = () => {
	// If we didn't get a fraisunit, we are adding a fraisunit
    if (!this.fraisunit) {
      this.add();
    } else { // If we didn't get a fraisunit, we are adding a fraisunit
      this.update();
    }
  }

  add = () => {
    this._fraisunitService.create(this.form.value).subscribe(
      result => {
        this._notificationService.success('Success', 'Fraisunit added successfuly');
        this._router.navigate(['./fraisunit-form', this.form.value.fraisunitid]);
      },
      error => {1
        if (error.status === this.CONFLICT_ERROR) {
          this._notificationService.error(error.statusText, 'Id already used in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  update = () => {
	Object.assign(this.fraisunit,this.form.value);
    this._fraisunitService.update(this.fraisunit).subscribe(
      result => this._notificationService.success('Success', 'Fraisunit edited successfuly'),
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  deleteConfirmation = () => {
    if (this.fraisunit.fraisunitid) {
      const dialogRef = this.dialog.open(DeleteDialogComponent, {
        data: `fraisunit: ${this.fraisunit.fraisunitid}`
      });
      dialogRef.afterClosed().subscribe(result => {
        if (result) {
          this.deleteBadge(this.fraisunit);
        }
      });
    }
  }

  deleteBadge = (fraisunit: Fraisunit): void => {
    // Call delete service
    this._fraisunitService.delete(fraisunit).subscribe(
      result => {
        this._router.navigate(['./fraisunit-list']);

        this._notificationService.success(
          'Deleted',
         // `The fraisunit entry with the id(s)='${fraisunitid}' was deleted successfuly`);
 		`The fraisunit entry with the id= was deleted successfuly`);
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }
}
