// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 16:11:30 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';
import { Router } from '@angular/router';
import { ActivatedRoute  } from '@angular/router';
import { MatDialog } from '@angular/material';

// Services imports
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { ContratfournisseurService } from './../services/contratfournisseur.service';
import { ApplicationStateService } from './../../../services/application-state.service';

// Models imports
import { Contratfournisseur } from '../contratfournisseur.model';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Ajout primeng
import {TableModule} from 'primeng/table';
import {PaginatorModule} from 'primeng/paginator';

@Component({
  selector: 'app-contratfournisseur-list',
  templateUrl: './contratfournisseur-list.component.html',
  styleUrls: ['./contratfournisseur-list.component.css'],
  providers: [DatePipe]
})
export class ContratfournisseurListComponent implements OnInit, OnChanges {

  public title = 'Liste de Contratfournisseurs';

  public listOfContratfournisseurs: Contratfournisseur[];


  _filter : string;
  @Input('filter') 
  set filter(value:string) {
	 this._filter = value;
     this.getAllContratfournisseurs();
  }

  get filter():string {
	return this._filter
  }

  @Input() createenable?: boolean = true;
  @Input() deleteenable?: boolean = true;
  @Input() updateenable?: boolean = true;
  @Input() incard?: boolean = true;

  private listId = 'CONTRATFOURNISSEUR_COMPONENT_LIST';

  private contratfournisseur: Contratfournisseur;

  private columnDefinitions = [
      { def: 'contact1', showMobile: true, display:'none', index:0},
      { def: 'tel1_portable', showMobile: true, display:'none', index:1},
      { def: 'tel1_travail', showMobile: true, display:'none', index:2},
      { def: 'tel1_domicile', showMobile: true, display:'none', index:3},
      { def: 'referencefournisseur', showMobile: true, display:'none', index:4},
      { def: 'avenant', showMobile: true, display:'none', index:5},
      { def: 'mail1', showMobile: true, display:'none', index:6},
      { def: 'adressefact', showMobile: true, display:'none', index:7},
      { def: 'contactfact', showMobile: true, display:'none', index:8},
      { def: 'categorie', showMobile: true, display:'none', index:9},
      { def: 'factcra', showMobile: true, display:'none', index:10},
      { def: 'dateenvoi', showMobile: true, display:'none', index:11},
      { def: 'dateretour', showMobile: true, display:'none', index:12},
      { def: 'arcurssaf', showMobile: true, display:'none', index:13},
      { def: 'echeancecontratfournisseur', showMobile: true, display:'none', index:14},
      { def: 'idfournisseur', showMobile: true, display:'table-cell', index:15},
      { def: 'contratfournisseurid', showMobile: true, display:'table-cell', index:16},
      { def: 'reference', showMobile: true, display:'table-cell', index:17},
      { def: 'datedebut', showMobile: true, display:'table-cell', index:18},
      { def: 'datefin', showMobile: true, display:'table-cell', index:19},
	];

  constructor(
    private _contratfournisseurService: ContratfournisseurService,
    private _router: Router,
    private _notificationService: NotificationService,
    public dialog: MatDialog,
	private _route: ActivatedRoute) { }

  ngOnInit() {
    // On init get all Contratfournisseurs
    //this.getAllContratfournisseurs();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Contratfournisseur list
    EmitterService.get(this.listId).subscribe((data: Contratfournisseur[]) => this.getAllContratfournisseurs());
  }

  ngOnChanges() { }


  /**
   * Get displayed columns (responsive)
   */
  getDisplayedColumns(): string[] {
	  const isMobile = ApplicationStateService.getIsMobileResolution();
	  return this.columnDefinitions
	    .filter(cd => !isMobile || cd.showMobile)
	    .map(cd => cd.def);
	}

  /**
   * Get all Contratfournisseur using the service ContratfournisseurService
   */
  getAllContratfournisseurs = (): void => {

	var options:any = { notPaged: true };
	
	if (this.filter) {
		if (this.filter == 'FULL') {
			options = { notPaged: true };
		}
		else {
			var filters = JSON.parse(this.filter);
			options = {params: filters,
						   notPaged: true};
		}

    	this._contratfournisseurService.getAll(options).subscribe(
      		(data: Contratfournisseur[]) => {
        		this.listOfContratfournisseurs = data;
      		},
      	error => {
        	this._notificationService.error(
          	'Error',
          	'An error occured when trying to reach the server');
    	});
	}
  }

  editContratfournisseur = (contratfournisseurid): void => {
    // Navigate to contratfournisseur form component
    this.goToContratfournisseurForm(contratfournisseurid);
  }

  deleteContratfournisseur = (contratfournisseurid): void => {

    const promise = new Promise((resolve, reject) => {
		// Call get service
		this._contratfournisseurService.get([contratfournisseurid]).subscribe(
        		(contratfournisseur: Contratfournisseur) => {
          							this.contratfournisseur = contratfournisseur;
          							resolve('done');
        						},
				error => {
          					this._notificationService.error(error.statusText, 'Error delete');
            				reject('error');
        				 });
	})
    .then(() => {
    	// Call delete service
    	this._contratfournisseurService.delete(this.contratfournisseur).subscribe(
      			result => {
       						 // Notify Contratfournisseur list to refresh
        					EmitterService.get(this.listId).emit(result);

        					this._notificationService.success(
          					'Deleted',
          					`The contratfournisseur entry with the id='${contratfournisseurid}' was deleted successfuly`);
     					  },
      			error => {
        					this._notificationService.error(
          					'Error',
          					'An error occured when trying to reach the server');
      					  });
  	})
  }

  goToContratfournisseurForm(contratfournisseurid) {
    this._router.navigate(['./contratfournisseur-form', contratfournisseurid]);
  }

  deleteConfirmation = (contratfournisseurid) => {
    const dialogRef = this.dialog.open(DeleteDialogComponent, {
      data: `contratfournisseur: ${contratfournisseurid}`
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteContratfournisseur(contratfournisseurid);
      }
    });
  }

}
