// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-05-04 ( Time 12:00:09 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-contratfournisseur-listheader',
  templateUrl: './contratfournisseur-listheader.component.html',
  styleUrls: ['./contratfournisseur-listheader.component.css'],
  providers: []
})
export class ContratfournisseurListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Contratfournisseurs';
  public filter:string = 'FULL';

  private columnDefinitions = [
      { def: 'idfournisseur', showMobile: true },
      { def: 'contratfournisseurid', showMobile: true },
      { def: 'reference', showMobile: true },
      { def: 'datedebut', showMobile: true },
      { def: 'datefin', showMobile: true },
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
