// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:35 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Rubriquefrais } from '../rubriquefrais.model';

@Injectable()
export class RubriquefraisService extends RestService<Rubriquefrais>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Rubriquefrais, 'rubriquefrais', injector);
    }

}
