// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 15:07:51 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';
import { Router } from '@angular/router';
import { ActivatedRoute  } from '@angular/router';
import { MatDialog } from '@angular/material';

// Services imports
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { EcheancecontratfournisseurService } from './../services/echeancecontratfournisseur.service';
import { ApplicationStateService } from './../../../services/application-state.service';

// Models imports
import { Echeancecontratfournisseur } from '../echeancecontratfournisseur.model';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Ajout primeng
import {TableModule} from 'primeng/table';
import {PaginatorModule} from 'primeng/paginator';

@Component({
  selector: 'app-echeancecontratfournisseur-list',
  templateUrl: './echeancecontratfournisseur-list.component.html',
  styleUrls: ['./echeancecontratfournisseur-list.component.css'],
  providers: [DatePipe]
})
export class EcheancecontratfournisseurListComponent implements OnInit, OnChanges {

  public title = 'Liste de Echeancecontratfournisseurs';

  public listOfEcheancecontratfournisseurs: Echeancecontratfournisseur[];


  _filter : string;
  @Input('filter') 
  set filter(value:string) {
	 this._filter = value;
     this.getAllEcheancecontratfournisseurs();
  }

  get filter():string {
	return this._filter
  }

  @Input() createenable?: boolean = true;
  @Input() deleteenable?: boolean = true;
  @Input() updateenable?: boolean = true;
  @Input() incard?: boolean = true;

  private listId = 'ECHEANCECONTRATFOURNISSEUR_COMPONENT_LIST';

  private echeancecontratfournisseur: Echeancecontratfournisseur;

  private columnDefinitions = [
      { def: 'montantht', showMobile: true, display:'none', index:0},
      { def: 'tauxtva', showMobile: true, display:'none', index:1},
      { def: 'echeancecontratfournisseurid', showMobile: true, display:'table-cell', index:2},
      { def: 'idcontratfournisseur', showMobile: true, display:'table-cell', index:3},
      { def: 'dateecheance', showMobile: true, display:'table-cell', index:4},
      { def: 'libelle', showMobile: true, display:'table-cell', index:5},
	];

  constructor(
    private _echeancecontratfournisseurService: EcheancecontratfournisseurService,
    private _router: Router,
    private _notificationService: NotificationService,
    public dialog: MatDialog,
	private _route: ActivatedRoute) { }

  ngOnInit() {
    // On init get all Echeancecontratfournisseurs
    //this.getAllEcheancecontratfournisseurs();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Echeancecontratfournisseur list
    EmitterService.get(this.listId).subscribe((data: Echeancecontratfournisseur[]) => this.getAllEcheancecontratfournisseurs());
  }

  ngOnChanges() { }


  /**
   * Get displayed columns (responsive)
   */
  getDisplayedColumns(): string[] {
	  const isMobile = ApplicationStateService.getIsMobileResolution();
	  return this.columnDefinitions
	    .filter(cd => !isMobile || cd.showMobile)
	    .map(cd => cd.def);
	}

  /**
   * Get all Echeancecontratfournisseur using the service EcheancecontratfournisseurService
   */
  getAllEcheancecontratfournisseurs = (): void => {

	var options:any = { notPaged: true };
	
	if (this.filter) {
		if (this.filter == 'FULL') {
			options = { notPaged: true };
		}
		else {
			var filters = JSON.parse(this.filter);
			options = {params: filters,
						   notPaged: true};
		}

    	this._echeancecontratfournisseurService.getAll(options).subscribe(
      		(data: Echeancecontratfournisseur[]) => {
        		this.listOfEcheancecontratfournisseurs = data;
      		},
      	error => {
        	this._notificationService.error(
          	'Error',
          	'An error occured when trying to reach the server');
    	});
	}
  }

  editEcheancecontratfournisseur = (echeancecontratfournisseurid): void => {
    // Navigate to echeancecontratfournisseur form component
    this.goToEcheancecontratfournisseurForm(echeancecontratfournisseurid);
  }

  deleteEcheancecontratfournisseur = (echeancecontratfournisseurid): void => {

    const promise = new Promise((resolve, reject) => {
		// Call get service
		this._echeancecontratfournisseurService.get([echeancecontratfournisseurid]).subscribe(
        		(echeancecontratfournisseur: Echeancecontratfournisseur) => {
          							this.echeancecontratfournisseur = echeancecontratfournisseur;
          							resolve('done');
        						},
				error => {
          					this._notificationService.error(error.statusText, 'Error delete');
            				reject('error');
        				 });
	})
    .then(() => {
    	// Call delete service
    	this._echeancecontratfournisseurService.delete(this.echeancecontratfournisseur).subscribe(
      			result => {
       						 // Notify Echeancecontratfournisseur list to refresh
        					EmitterService.get(this.listId).emit(result);

        					this._notificationService.success(
          					'Deleted',
          					`The echeancecontratfournisseur entry with the id='${echeancecontratfournisseurid}' was deleted successfuly`);
     					  },
      			error => {
        					this._notificationService.error(
          					'Error',
          					'An error occured when trying to reach the server');
      					  });
  	})
  }

  goToEcheancecontratfournisseurForm(echeancecontratfournisseurid) {
    this._router.navigate(['./echeancecontratfournisseur-form', echeancecontratfournisseurid]);
  }

  deleteConfirmation = (echeancecontratfournisseurid) => {
    const dialogRef = this.dialog.open(DeleteDialogComponent, {
      data: `echeancecontratfournisseur: ${echeancecontratfournisseurid}`
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteEcheancecontratfournisseur(echeancecontratfournisseurid);
      }
    });
  }

}
