// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 15:07:51 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-echeancecontratfournisseur-listheader',
  templateUrl: './echeancecontratfournisseur-listheader.component.html',
  styleUrls: ['./echeancecontratfournisseur-listheader.component.css'],
  providers: []
})
export class EcheancecontratfournisseurListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Echeancecontratfournisseurs';
  public filter:string = 'FULL';

  private columnDefinitions = [
      { def: 'echeancecontratfournisseurid', showMobile: true },
      { def: 'idcontratfournisseur', showMobile: true },
      { def: 'dateecheance', showMobile: true },
      { def: 'libelle', showMobile: true },
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
