// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:31 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Frais } from '../frais.model';

@Injectable()
export class FraisService extends RestService<Frais>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Frais, 'frais', injector);
    }

}
