// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:15 )


import { Resource } from 'angular4-hal';

export class Baremekm extends Resource {
	annee: string; // Wrapper Type : String
	cv: string; // Wrapper Type : String
	baremefisc1: string; // Wrapper Type : String
	baremefisc2: string; // Wrapper Type : String
	baremefisc3: string; // Wrapper Type : String
	bareme: number; // Wrapper Type : Number
}
