// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:34 )


import { Resource } from 'angular4-hal';

export class Rubrique extends Resource {
	coderubrique: string; // Wrapper Type : String
	ordre: string; // Wrapper Type : String
	niveau: string; // Wrapper Type : String
	nom: string; // Wrapper Type : String
	profils: string; // Wrapper Type : String
	conge: boolean; // Wrapper Type : Boolean
	typerubrique: string; // Wrapper Type : String
}
