// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:41 )


import { Resource } from 'angular4-hal';

export class Reliquat extends Resource {
	codeexercice: string; // Wrapper Type : String
	idconsultant: number; // Wrapper Type : Number
	codetypeactivite: string; // Wrapper Type : String
	quantite: number; // Wrapper Type : Number
	comment: string; // Wrapper Type : String
}
