// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:24 )


import { Resource } from 'angular4-hal';

export class Echeancecontrat extends Resource {
	echeancecontratid: number; // Wrapper Type : Number
	idcontrat: number; // Wrapper Type : Number
	dateecheance: Date; // Wrapper Type : Date
	libelle: string; // Wrapper Type : String
	montantht: number; // Wrapper Type : Number
	tauxtva: number; // Wrapper Type : Number
}
