// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:23 )


import { Resource } from 'angular4-hal';

export class Document extends Resource {
	documentid: number; // Wrapper Type : Number
	type: string; // Wrapper Type : String
	ref: string; // Wrapper Type : String
	nom: string; // Wrapper Type : String
}
