// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:43 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Rubrique } from '../rubrique.model';

@Injectable()
export class RubriqueService extends RestService<Rubrique>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Rubrique, 'rubrique', injector);
    }

}
