// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:28 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-frais-listheader',
  templateUrl: './frais-listheader.component.html',
  styleUrls: ['./frais-listheader.component.css'],
  providers: []
})
export class FraisListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Fraiss';
  public filter:string = 'FULL';

  private columnDefinitions = [
      { def: 'fraisid', showMobile: true },
      { def: 'idconsultant', showMobile: true },
      { def: 'codeperiode', showMobile: true },
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
