// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 16:11:44 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';
import { Router } from '@angular/router';
import { ActivatedRoute  } from '@angular/router';
import { MatDialog } from '@angular/material';

// Services imports
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { ReliquatService } from './../services/reliquat.service';
import { ApplicationStateService } from './../../../services/application-state.service';

// Models imports
import { Reliquat } from '../reliquat.model';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Ajout primeng
import {TableModule} from 'primeng/table';
import {PaginatorModule} from 'primeng/paginator';

@Component({
  selector: 'app-reliquat-list',
  templateUrl: './reliquat-list.component.html',
  styleUrls: ['./reliquat-list.component.css'],
  providers: [DatePipe]
})
export class ReliquatListComponent implements OnInit, OnChanges {

  public title = 'Liste de Reliquats';

  public listOfReliquats: Reliquat[];


  _filter : string;
  @Input('filter') 
  set filter(value:string) {
	 this._filter = value;
     this.getAllReliquats();
  }

  get filter():string {
	return this._filter
  }

  @Input() createenable?: boolean = true;
  @Input() deleteenable?: boolean = true;
  @Input() updateenable?: boolean = true;
  @Input() incard?: boolean = true;

  private listId = 'RELIQUAT_COMPONENT_LIST';

  private reliquat: Reliquat;

  private columnDefinitions = [
      { def: 'quantite', showMobile: true, display:'none', index:0},
      { def: 'comment', showMobile: true, display:'none', index:1},
      { def: 'codeexercice', showMobile: true, display:'table-cell', index:2},
      { def: 'idconsultant', showMobile: true, display:'table-cell', index:3},
      { def: 'codetypeactivite', showMobile: true, display:'table-cell', index:4},
	];

  constructor(
    private _reliquatService: ReliquatService,
    private _router: Router,
    private _notificationService: NotificationService,
    public dialog: MatDialog,
	private _route: ActivatedRoute) { }

  ngOnInit() {
    // On init get all Reliquats
    //this.getAllReliquats();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Reliquat list
    EmitterService.get(this.listId).subscribe((data: Reliquat[]) => this.getAllReliquats());
  }

  ngOnChanges() { }


  /**
   * Get displayed columns (responsive)
   */
  getDisplayedColumns(): string[] {
	  const isMobile = ApplicationStateService.getIsMobileResolution();
	  return this.columnDefinitions
	    .filter(cd => !isMobile || cd.showMobile)
	    .map(cd => cd.def);
	}

  /**
   * Get all Reliquat using the service ReliquatService
   */
  getAllReliquats = (): void => {

	var options:any = { notPaged: true };
	
	if (this.filter) {
		if (this.filter == 'FULL') {
			options = { notPaged: true };
		}
		else {
			var filters = JSON.parse(this.filter);
			options = {params: filters,
						   notPaged: true};
		}

    	this._reliquatService.getAll(options).subscribe(
      		(data: Reliquat[]) => {
        		this.listOfReliquats = data;
      		},
      	error => {
        	this._notificationService.error(
          	'Error',
          	'An error occured when trying to reach the server');
    	});
	}
  }

  editReliquat = (codeexercice, idconsultant, codetypeactivite): void => {
    // Navigate to reliquat form component
    this.goToReliquatForm(codeexercice, idconsultant, codetypeactivite);
  }

  deleteReliquat = (codeexercice, idconsultant, codetypeactivite): void => {

    const promise = new Promise((resolve, reject) => {
		// Call get service
		this._reliquatService.get([codeexercice, idconsultant, codetypeactivite]).subscribe(
        		(reliquat: Reliquat) => {
          							this.reliquat = reliquat;
          							resolve('done');
        						},
				error => {
          					this._notificationService.error(error.statusText, 'Error delete');
            				reject('error');
        				 });
	})
    .then(() => {
    	// Call delete service
    	this._reliquatService.delete(this.reliquat).subscribe(
      			result => {
       						 // Notify Reliquat list to refresh
        					EmitterService.get(this.listId).emit(result);

        					this._notificationService.success(
          					'Deleted',
          					`The reliquat entry with the id='${codeexercice}, ${idconsultant}, ${codetypeactivite}' was deleted successfuly`);
     					  },
      			error => {
        					this._notificationService.error(
          					'Error',
          					'An error occured when trying to reach the server');
      					  });
  	})
  }

  goToReliquatForm(codeexercice, idconsultant, codetypeactivite) {
    this._router.navigate(['./reliquat-form', codeexercice, idconsultant, codetypeactivite]);
  }

  deleteConfirmation = (codeexercice, idconsultant, codetypeactivite) => {
    const dialogRef = this.dialog.open(DeleteDialogComponent, {
      data: `reliquat: ${codeexercice}, ${idconsultant}, ${codetypeactivite}`
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteReliquat(codeexercice, idconsultant, codetypeactivite);
      }
    });
  }

}
