// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:34 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-reliquat-listheader',
  templateUrl: './reliquat-listheader.component.html',
  styleUrls: ['./reliquat-listheader.component.css'],
  providers: []
})
export class ReliquatListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Reliquats';
  public filter:string = 'FULL';

  private columnDefinitions = [
      { def: 'codeexercice', showMobile: true },
      { def: 'idconsultant', showMobile: true },
      { def: 'codetypeactivite', showMobile: true },
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
