// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 16:11:25 )

// Modules imports
import { NotificationService } from './../../../services/notification.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material';
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Models and services imports
import { Conge } from './../conge.model';
import { CongeService } from './../services/conge.service';
import * as _ from 'underscore';

// Pour gestion des listes
import { ListeService } from './../../../entities/liste/services/liste.service';
import { Liste } from './../../../entities/liste/liste.model';

import { Lov } from './../../../common/lov';
import {SelectItem} from 'primeng/api';

@Component({
  selector: 'app-conge-form',
  templateUrl: './conge-form.component.html',
  styleUrls: ['./conge-form.component.css'],
  providers: [DatePipe]
})
export class CongeFormComponent extends Lov implements OnInit {

  // HTTP status code
  readonly NOT_FOUND_ERROR = 404;
  readonly CONFLICT_ERROR = 409;
  readonly INTERNAL_SERVER_ERROR = 500;

  public title = 'Formulaire Conge';
  public form: FormGroup;

  // Définition des filtres

  public conge: Conge;
  private ids;

  // Définition des LOV

  constructor(
	private _listeService: ListeService,         // Pour gestion des listes
    private _congeService: CongeService,
    private _route: ActivatedRoute,
    private _router: Router,
    private _formBuilder: FormBuilder,
    private _notificationService: NotificationService,
    public dialog: MatDialog) {
		super(_listeService,_notificationService);
 	}

  ngOnInit() {
    this.getIdFromRouteParams();
    this.initForm();
  }

  getIdFromRouteParams = () => {
    this._route.params.subscribe(p => {
        this.ids = _.values(p);
    });
  }

  initForm = () => {
    this.form = this._formBuilder.group(this.getNewForm());
    if (!_.isEmpty(this.ids)) {
      this.load();
    }

	/* Chargement des LOVs */
  }

  getNewForm = (conge?: Conge) => {
    return {
      congeid: [{
          value: (conge ? conge.congeid : ''),
          disabled: true
      }],      idconsultant: [
        (conge ? conge.idconsultant : ''),
        Validators.required
      ],
      codeexercice: [
        (conge ? conge.codeexercice : '')
      ],
      datedebut: [
        (conge ? conge.datedebut : null)
      ],
      datefin: [
        (conge ? conge.datefin : null)
      ],
      commentaire: [
        (conge ? conge.commentaire : '')
      ],
      statut: [
        (conge ? conge.statut : '')
      ],
      nbj: [
        (conge ? conge.nbj : '')
      ],
      autorisationClient: [
        (conge ? conge.autorisationClient : '')
      ],
      dateconsultant: [
        (conge ? conge.dateconsultant : null)
      ],
      dateprerequis: [
        (conge ? conge.dateprerequis : null)
      ],
      quiprerequis: [
        (conge ? conge.quiprerequis : '')
      ]
    };
  }


  load = () => {
	// Concaténer les ids mais séparé par / et non ,
	var param : String = '';
	
	for (var i=0;i<this.ids.length;i++) {
		param = param + this.ids[i];
		if (i != (this.ids.length-1)) {
			param = param + '/';
		}
	}
    this._congeService.get(param).subscribe(
      (conge: Conge) => {
        this.conge = conge;
        this.form = this._formBuilder.group(this.getNewForm(this.conge));
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
 	  },
      () => {
		// Valorisation des filtres
      });
  }

  save = () => {
	// If we didn't get a conge, we are adding a conge
    if (!this.conge) {
      this.add();
    } else { // If we didn't get a conge, we are adding a conge
      this.update();
    }
  }

  add = () => {
    this._congeService.create(this.form.value).subscribe(
      result => {
        this._notificationService.success('Success', 'Conge added successfuly');
        this._router.navigate(['./conge-form', this.form.value.congeid]);
      },
      error => {1
        if (error.status === this.CONFLICT_ERROR) {
          this._notificationService.error(error.statusText, 'Id already used in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  update = () => {
	Object.assign(this.conge,this.form.value);
    this._congeService.update(this.conge).subscribe(
      result => this._notificationService.success('Success', 'Conge edited successfuly'),
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  deleteConfirmation = () => {
    if (this.conge.congeid) {
      const dialogRef = this.dialog.open(DeleteDialogComponent, {
        data: `conge: ${this.conge.congeid}`
      });
      dialogRef.afterClosed().subscribe(result => {
        if (result) {
          this.deleteBadge(this.conge);
        }
      });
    }
  }

  deleteBadge = (conge: Conge): void => {
    // Call delete service
    this._congeService.delete(conge).subscribe(
      result => {
        this._router.navigate(['./conge-list']);

        this._notificationService.success(
          'Deleted',
         // `The conge entry with the id(s)='${congeid}' was deleted successfuly`);
 		`The conge entry with the id= was deleted successfuly`);
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }
}
