// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-02-20 ( Time 13:54:32 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Menu } from '../menu.model';

@Injectable()
export class MenuService extends RestService<Menu>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Menu, 'menu', injector);
    }

}
