// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:17 )

// Modules imports
import { NotificationService } from './../../../services/notification.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material';
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Models and services imports
import { Client } from './../client.model';
import { ClientService } from './../services/client.service';
import * as _ from 'underscore';

// Pour gestion des listes
import { ListeService } from './../../../entities/liste/services/liste.service';
import { Liste } from './../../../entities/liste/liste.model';

import { Lov } from './../../../common/lov';
import {SelectItem} from 'primeng/api';

@Component({
  selector: 'app-client-form',
  templateUrl: './client-form.component.html',
  styleUrls: ['./client-form.component.css'],
  providers: [DatePipe]
})
export class ClientFormComponent extends Lov implements OnInit {

  // HTTP status code
  readonly NOT_FOUND_ERROR = 404;
  readonly CONFLICT_ERROR = 409;
  readonly INTERNAL_SERVER_ERROR = 500;

  public title = 'Formulaire Client';
  public form: FormGroup;

  // Définition des filtres

  public client: Client;
  private ids;

  // Définition des LOV

  constructor(
	private _listeService: ListeService,         // Pour gestion des listes
    private _clientService: ClientService,
    private _route: ActivatedRoute,
    private _router: Router,
    private _formBuilder: FormBuilder,
    private _notificationService: NotificationService,
    public dialog: MatDialog) {
		super(_listeService,_notificationService);
 	}

  ngOnInit() {
    this.getIdFromRouteParams();
    this.initForm();
  }

  getIdFromRouteParams = () => {
    this._route.params.subscribe(p => {
        this.ids = _.values(p);
    });
  }

  initForm = () => {
    this.form = this._formBuilder.group(this.getNewForm());
    if (!_.isEmpty(this.ids)) {
      this.load();
    }

	/* Chargement des LOVs */
  }

  getNewForm = (client?: Client) => {
    return {
      clientid: [{
          value: (client ? client.clientid : ''),
          disabled: true
      }],      raisonsociale: [
        (client ? client.raisonsociale : '')
      ],
      adresse1: [
        (client ? client.adresse1 : '')
      ],
      adresse2: [
        (client ? client.adresse2 : '')
      ],
      contact1: [
        (client ? client.contact1 : '')
      ],
      tel1Portable: [
        (client ? client.tel1Portable : '')
      ],
      tel1Travail: [
        (client ? client.tel1Travail : '')
      ],
      tel1Domicile: [
        (client ? client.tel1Domicile : '')
      ],
      contact2: [
        (client ? client.contact2 : '')
      ],
      tel2Portable: [
        (client ? client.tel2Portable : '')
      ],
      tel2Travail: [
        (client ? client.tel2Travail : '')
      ],
      tel2Domicile: [
        (client ? client.tel2Domicile : '')
      ],
      trigramme: [
        (client ? client.trigramme : '')
      ]
    };
  }


  load = () => {
	// Concaténer les ids mais séparé par / et non ,
	var param : String = '';
	
	for (var i=0;i<this.ids.length;i++) {
		param = param + this.ids[i];
		if (i != (this.ids.length-1)) {
			param = param + '/';
		}
	}
    this._clientService.get(param).subscribe(
      (client: Client) => {
        this.client = client;
        this.form = this._formBuilder.group(this.getNewForm(this.client));
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
 	  },
      () => {
		// Valorisation des filtres
      });
  }

  save = () => {
	// If we didn't get a client, we are adding a client
    if (!this.client) {
      this.add();
    } else { // If we didn't get a client, we are adding a client
      this.update();
    }
  }

  add = () => {
    this._clientService.create(this.form.value).subscribe(
      result => {
        this._notificationService.success('Success', 'Client added successfuly');
        this._router.navigate(['./client-form', this.form.value.clientid]);
      },
      error => {1
        if (error.status === this.CONFLICT_ERROR) {
          this._notificationService.error(error.statusText, 'Id already used in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  update = () => {
	Object.assign(this.client,this.form.value);
    this._clientService.update(this.client).subscribe(
      result => this._notificationService.success('Success', 'Client edited successfuly'),
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  deleteConfirmation = () => {
    if (this.client.clientid) {
      const dialogRef = this.dialog.open(DeleteDialogComponent, {
        data: `client: ${this.client.clientid}`
      });
      dialogRef.afterClosed().subscribe(result => {
        if (result) {
          this.deleteBadge(this.client);
        }
      });
    }
  }

  deleteBadge = (client: Client): void => {
    // Call delete service
    this._clientService.delete(client).subscribe(
      result => {
        this._router.navigate(['./client-list']);

        this._notificationService.success(
          'Deleted',
         // `The client entry with the id(s)='${clientid}' was deleted successfuly`);
 		`The client entry with the id= was deleted successfuly`);
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }
}
