// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:43 )

// Modules imports
import { NotificationService } from './../../../services/notification.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material';
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Models and services imports
import { Rubrique } from './../rubrique.model';
import { RubriqueService } from './../services/rubrique.service';
import * as _ from 'underscore';

// Pour gestion des listes
import { ListeService } from './../../../entities/liste/services/liste.service';
import { Liste } from './../../../entities/liste/liste.model';

import { Lov } from './../../../common/lov';
import {SelectItem} from 'primeng/api';

@Component({
  selector: 'app-rubrique-form',
  templateUrl: './rubrique-form.component.html',
  styleUrls: ['./rubrique-form.component.css'],
  providers: [DatePipe]
})
export class RubriqueFormComponent extends Lov implements OnInit {

  // HTTP status code
  readonly NOT_FOUND_ERROR = 404;
  readonly CONFLICT_ERROR = 409;
  readonly INTERNAL_SERVER_ERROR = 500;

  public title = 'Formulaire Rubrique';
  public form: FormGroup;

  // Définition des filtres

  public rubrique: Rubrique;
  private ids;

  // Définition des LOV

  constructor(
	private _listeService: ListeService,         // Pour gestion des listes
    private _rubriqueService: RubriqueService,
    private _route: ActivatedRoute,
    private _router: Router,
    private _formBuilder: FormBuilder,
    private _notificationService: NotificationService,
    public dialog: MatDialog) {
		super(_listeService,_notificationService);
 	}

  ngOnInit() {
    this.getIdFromRouteParams();
    this.initForm();
  }

  getIdFromRouteParams = () => {
    this._route.params.subscribe(p => {
        this.ids = _.values(p);
    });
  }

  initForm = () => {
    this.form = this._formBuilder.group(this.getNewForm());
    if (!_.isEmpty(this.ids)) {
      this.load();
    }

	/* Chargement des LOVs */
  }

  getNewForm = (rubrique?: Rubrique) => {
    return {
      coderubrique: [
          (rubrique ? rubrique.coderubrique : ''),
          Validators.required
      ],
      ordre: [
        (rubrique ? rubrique.ordre : '')
      ],
      niveau: [
        (rubrique ? rubrique.niveau : '')
      ],
      nom: [
        (rubrique ? rubrique.nom : '')
      ],
      profils: [
        (rubrique ? rubrique.profils : '')
      ],
      conge: [
        (rubrique ? rubrique.conge : '')
      ],
      typerubrique: [
        (rubrique ? rubrique.typerubrique : ''),
        Validators.required
      ]
    };
  }


  load = () => {
	// Concaténer les ids mais séparé par / et non ,
	var param : String = '';
	
	for (var i=0;i<this.ids.length;i++) {
		param = param + this.ids[i];
		if (i != (this.ids.length-1)) {
			param = param + '/';
		}
	}
    this._rubriqueService.get(param).subscribe(
      (rubrique: Rubrique) => {
        this.rubrique = rubrique;
        this.form = this._formBuilder.group(this.getNewForm(this.rubrique));
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
 	  },
      () => {
		// Valorisation des filtres
      });
  }

  save = () => {
	// If we didn't get a rubrique, we are adding a rubrique
    if (!this.rubrique) {
      this.add();
    } else { // If we didn't get a rubrique, we are adding a rubrique
      this.update();
    }
  }

  add = () => {
    this._rubriqueService.create(this.form.value).subscribe(
      result => {
        this._notificationService.success('Success', 'Rubrique added successfuly');
        this._router.navigate(['./rubrique-form', this.form.value.coderubrique]);
      },
      error => {1
        if (error.status === this.CONFLICT_ERROR) {
          this._notificationService.error(error.statusText, 'Id already used in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  update = () => {
	Object.assign(this.rubrique,this.form.value);
    this._rubriqueService.update(this.rubrique).subscribe(
      result => this._notificationService.success('Success', 'Rubrique edited successfuly'),
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  deleteConfirmation = () => {
    if (this.rubrique.coderubrique) {
      const dialogRef = this.dialog.open(DeleteDialogComponent, {
        data: `rubrique: ${this.rubrique.coderubrique}`
      });
      dialogRef.afterClosed().subscribe(result => {
        if (result) {
          this.deleteBadge(this.rubrique);
        }
      });
    }
  }

  deleteBadge = (rubrique: Rubrique): void => {
    // Call delete service
    this._rubriqueService.delete(rubrique).subscribe(
      result => {
        this._router.navigate(['./rubrique-list']);

        this._notificationService.success(
          'Deleted',
         // `The rubrique entry with the id(s)='${coderubrique}' was deleted successfuly`);
 		`The rubrique entry with the id= was deleted successfuly`);
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }
}
