// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:23 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';
import { Router } from '@angular/router';
import { ActivatedRoute  } from '@angular/router';
import { MatDialog } from '@angular/material';

// Services imports
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { DocumentService } from './../services/document.service';
import { ApplicationStateService } from './../../../services/application-state.service';

// Models imports
import { Document } from '../document.model';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Ajout primeng
import {TableModule} from 'primeng/table';
import {PaginatorModule} from 'primeng/paginator';

@Component({
  selector: 'app-document-list',
  templateUrl: './document-list.component.html',
  styleUrls: ['./document-list.component.css'],
  providers: [DatePipe]
})
export class DocumentListComponent implements OnInit, OnChanges {

  public title = 'Liste de Documents';

  public listOfDocuments: Document[];


  _filter : string;
  @Input('filter') 
  set filter(value:string) {
	 this._filter = value;
     this.getAllDocuments();
  }

  get filter():string {
	return this._filter
  }

  @Input() createenable?: boolean = true;
  @Input() deleteenable?: boolean = true;
  @Input() updateenable?: boolean = true;
  @Input() incard?: boolean = true;

  private listId = 'DOCUMENT_COMPONENT_LIST';

  private document: Document;

  private columnDefinitions = [
      { def: 'documentid', showMobile: true, display:'table-cell', index:0},
      { def: 'type', showMobile: true, display:'table-cell', index:1},
      { def: 'ref', showMobile: true, display:'table-cell', index:2},
      { def: 'nom', showMobile: true, display:'table-cell', index:3},
	];

  constructor(
    private _documentService: DocumentService,
    private _router: Router,
    private _notificationService: NotificationService,
    public dialog: MatDialog,
	private _route: ActivatedRoute) { }

  ngOnInit() {
    // On init get all Documents
    //this.getAllDocuments();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Document list
    EmitterService.get(this.listId).subscribe((data: Document[]) => this.getAllDocuments());
  }

  ngOnChanges() { }


  /**
   * Get displayed columns (responsive)
   */
  getDisplayedColumns(): string[] {
	  const isMobile = ApplicationStateService.getIsMobileResolution();
	  return this.columnDefinitions
	    .filter(cd => !isMobile || cd.showMobile)
	    .map(cd => cd.def);
	}

  /**
   * Get all Document using the service DocumentService
   */
  getAllDocuments = (): void => {

	var options:any = { notPaged: true };
	
	if (this.filter) {
		if (this.filter == 'FULL') {
			options = { notPaged: true };
		}
		else {
			var filters = JSON.parse(this.filter);
			options = {params: filters,
						   notPaged: true};
		}

    	this._documentService.getAll(options).subscribe(
      		(data: Document[]) => {
        		this.listOfDocuments = data;
      		},
      	error => {
        	this._notificationService.error(
          	'Error',
          	'An error occured when trying to reach the server');
    	});
	}
  }

  editDocument = (documentid): void => {
    // Navigate to document form component
    this.goToDocumentForm(documentid);
  }

  deleteDocument = (documentid): void => {

    const promise = new Promise((resolve, reject) => {
		// Call get service
		this._documentService.get(documentid).subscribe(
        		(document: Document) => {
          							this.document = document;
          							resolve('done');
        						},
				error => {
          					this._notificationService.error(error.statusText, 'Error delete');
            				reject('error');
        				 });
	})
    .then(() => {
    	// Call delete service
    	this._documentService.delete(this.document).subscribe(
      			result => {
       						 // Notify Document list to refresh
        					EmitterService.get(this.listId).emit(result);

        					this._notificationService.success(
          					'Deleted',
          					`The document entry with the id='${documentid}' was deleted successfuly`);
     					  },
      			error => {
        					this._notificationService.error(
          					'Error',
          					'An error occured when trying to reach the server');
      					  });
  	})
  }

  goToDocumentForm(documentid) {
    this._router.navigate(['./document-form', documentid]);
  }

  deleteConfirmation = (documentid) => {
    const dialogRef = this.dialog.open(DeleteDialogComponent, {
      data: `document: ${documentid}`
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteDocument(documentid);
      }
    });
  }

}
