// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-03-24 ( Time 15:05:55 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Liste } from '../liste.model';
import { Observable } from 'rxjs/Observable'

@Injectable()
export class ListeService extends RestService<Liste>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Liste, 'liste', injector);
    }

    /**
     * searchByNomliste
     * @param nomliste string
     */
  public searchByNomliste(nomliste: string): Observable<Liste[]> {
    let options: any = {params: [
								],
                    	notPaged:true
					   };
    return this.search('searchByNomliste/'+nomliste, options);
  }

}
