// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:29 )


import { Resource } from 'angular4-hal';

export class Exercice extends Resource {
	code: string; // Wrapper Type : String
	ouvert: boolean; // Wrapper Type : Boolean
}
