// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-20 ( Time 13:25:09 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-liste-listheader',
  templateUrl: './liste-listheader.component.html',
  styleUrls: ['./liste-listheader.component.css'],
  providers: []
})
export class ListeListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Listes';
  public filter:string = 'FULL';

  private columnDefinitions = [
      { def: 'nomliste', showMobile: true },
      { def: 'codeelement', showMobile: true },
      { def: 'nomelement', showMobile: true },
      { def: 'ordretri', showMobile: true },
      { def: 'image', showMobile: true },
      { def: 'defaut', showMobile: true },
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
