// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:16 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-baremekm-listheader',
  templateUrl: './baremekm-listheader.component.html',
  styleUrls: ['./baremekm-listheader.component.css'],
  providers: []
})
export class BaremekmListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Baremekms';
  public filter:string = 'FULL';

  private columnDefinitions = [
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
