// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-05-04 ( Time 16:33:24 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-baremekm-listheader',
  templateUrl: './baremekm-listheader.component.html',
  styleUrls: ['./baremekm-listheader.component.css'],
  providers: []
})
export class BaremekmListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Baremekms';
  public filter:string = 'FULL';

  private columnDefinitions = [
      { def: 'annee', showMobile: true },
      { def: 'cv', showMobile: true },
      { def: 'baremefisc1', showMobile: true },
      { def: 'baremefisc2', showMobile: true },
      { def: 'baremefisc3', showMobile: true },
      { def: 'bareme', showMobile: true },
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
