// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:29 )


import { Resource } from 'angular4-hal';

export class Liencontrat extends Resource {
	idcontratclient: number; // Wrapper Type : Number
	idconsultantclient: number; // Wrapper Type : Number
	idcontratfournisseur: number; // Wrapper Type : Number
	idconsultantfournisseur: number; // Wrapper Type : Number
}
