// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:20 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-consultantcontrat-listheader',
  templateUrl: './consultantcontrat-listheader.component.html',
  styleUrls: ['./consultantcontrat-listheader.component.css'],
  providers: []
})
export class ConsultantcontratListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Consultantcontrats';
  public filter:string = 'FULL';

  private columnDefinitions = [
      { def: 'idconsultant', showMobile: true },
      { def: 'idcontrat', showMobile: true },
      { def: 'datedebut', showMobile: true },
      { def: 'datefin', showMobile: true },
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
