// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:41 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-profil-listheader',
  templateUrl: './profil-listheader.component.html',
  styleUrls: ['./profil-listheader.component.css'],
  providers: []
})
export class ProfilListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Profils';
  public filter:string = 'FULL';

  private columnDefinitions = [
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
