// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:41 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';
import { Router } from '@angular/router';
import { ActivatedRoute  } from '@angular/router';
import { MatDialog } from '@angular/material';

// Services imports
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { ProfilService } from './../services/profil.service';
import { ApplicationStateService } from './../../../services/application-state.service';

// Models imports
import { Profil } from '../profil.model';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Ajout primeng
import {TableModule} from 'primeng/table';
import {PaginatorModule} from 'primeng/paginator';

@Component({
  selector: 'app-profil-list',
  templateUrl: './profil-list.component.html',
  styleUrls: ['./profil-list.component.css'],
  providers: [DatePipe]
})
export class ProfilListComponent implements OnInit, OnChanges {

  public title = 'Liste de Profils';

  public listOfProfils: Profil[];


  _filter : string;
  @Input('filter') 
  set filter(value:string) {
	 this._filter = value;
     this.getAllProfils();
  }

  get filter():string {
	return this._filter
  }

  @Input() createenable?: boolean = true;
  @Input() deleteenable?: boolean = true;
  @Input() updateenable?: boolean = true;
  @Input() incard?: boolean = true;

  private listId = 'PROFIL_COMPONENT_LIST';

  private profil: Profil;

  private columnDefinitions = [
	];

  constructor(
    private _profilService: ProfilService,
    private _router: Router,
    private _notificationService: NotificationService,
    public dialog: MatDialog,
	private _route: ActivatedRoute) { }

  ngOnInit() {
    // On init get all Profils
    //this.getAllProfils();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Profil list
    EmitterService.get(this.listId).subscribe((data: Profil[]) => this.getAllProfils());
  }

  ngOnChanges() { }


  /**
   * Get displayed columns (responsive)
   */
  getDisplayedColumns(): string[] {
	  const isMobile = ApplicationStateService.getIsMobileResolution();
	  return this.columnDefinitions
	    .filter(cd => !isMobile || cd.showMobile)
	    .map(cd => cd.def);
	}

  /**
   * Get all Profil using the service ProfilService
   */
  getAllProfils = (): void => {

	var options:any = { notPaged: true };
	
	if (this.filter) {
		if (this.filter == 'FULL') {
			options = { notPaged: true };
		}
		else {
			var filters = JSON.parse(this.filter);
			options = {params: filters,
						   notPaged: true};
		}

    	this._profilService.getAll(options).subscribe(
      		(data: Profil[]) => {
        		this.listOfProfils = data;
      		},
      	error => {
        	this._notificationService.error(
          	'Error',
          	'An error occured when trying to reach the server');
    	});
	}
  }

  editProfil = (code): void => {
    // Navigate to profil form component
    this.goToProfilForm(code);
  }

  deleteProfil = (code): void => {

    const promise = new Promise((resolve, reject) => {
		// Call get service
		this._profilService.get([code]).subscribe(
        		(profil: Profil) => {
          							this.profil = profil;
          							resolve('done');
        						},
				error => {
          					this._notificationService.error(error.statusText, 'Error delete');
            				reject('error');
        				 });
	})
    .then(() => {
    	// Call delete service
    	this._profilService.delete(this.profil).subscribe(
      			result => {
       						 // Notify Profil list to refresh
        					EmitterService.get(this.listId).emit(result);

        					this._notificationService.success(
          					'Deleted',
          					`The profil entry with the id='${code}' was deleted successfuly`);
     					  },
      			error => {
        					this._notificationService.error(
          					'Error',
          					'An error occured when trying to reach the server');
      					  });
  	})
  }

  goToProfilForm(code) {
    this._router.navigate(['./profil-form', code]);
  }

  deleteConfirmation = (code) => {
    const dialogRef = this.dialog.open(DeleteDialogComponent, {
      data: `profil: ${code}`
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteProfil(code);
      }
    });
  }

}
