// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-13 ( Time 10:36:20 )

import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home-list',
  templateUrl: './home-list.component.html',
  styleUrls: ['./home-list.component.css']
})
export class HomeListComponent implements OnInit {

  public navigation = [
		{ title: 'Alerte', routerLink: 'alerte-list' }
  ];

  constructor() { }

  ngOnInit() {
  }

}
