// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:27 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';
import { Router } from '@angular/router';
import { ActivatedRoute  } from '@angular/router';
import { MatDialog } from '@angular/material';

// Services imports
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { FournisseurService } from './../services/fournisseur.service';
import { ApplicationStateService } from './../../../services/application-state.service';

// Models imports
import { Fournisseur } from '../fournisseur.model';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Ajout primeng
import {TableModule} from 'primeng/table';
import {PaginatorModule} from 'primeng/paginator';

@Component({
  selector: 'app-fournisseur-list',
  templateUrl: './fournisseur-list.component.html',
  styleUrls: ['./fournisseur-list.component.css'],
  providers: [DatePipe]
})
export class FournisseurListComponent implements OnInit, OnChanges {

  public title = 'Liste de Fournisseurs';

  public listOfFournisseurs: Fournisseur[];


  _filter : string;
  @Input('filter') 
  set filter(value:string) {
	 this._filter = value;
     this.getAllFournisseurs();
  }

  get filter():string {
	return this._filter
  }

  @Input() createenable?: boolean = true;
  @Input() deleteenable?: boolean = true;
  @Input() updateenable?: boolean = true;
  @Input() incard?: boolean = true;

  private listId = 'FOURNISSEUR_COMPONENT_LIST';

  private fournisseur: Fournisseur;

  private columnDefinitions = [
      { def: 'adresse1', showMobile: true, display:'none', index:0},
      { def: 'adresse2', showMobile: true, display:'none', index:1},
      { def: 'tel1_domicile', showMobile: true, display:'none', index:2},
      { def: 'contact2', showMobile: true, display:'none', index:3},
      { def: 'tel2_portable', showMobile: true, display:'none', index:4},
      { def: 'tel2_travail', showMobile: true, display:'none', index:5},
      { def: 'tel2_domicile', showMobile: true, display:'none', index:6},
      { def: 'fournisseurid', showMobile: true, display:'table-cell', index:7},
      { def: 'trigramme', showMobile: true, display:'table-cell', index:8},
      { def: 'raisonsociale', showMobile: true, display:'table-cell', index:9},
      { def: 'contact1', showMobile: true, display:'table-cell', index:10},
      { def: 'tel1_portable', showMobile: true, display:'table-cell', index:11},
      { def: 'tel1_travail', showMobile: true, display:'table-cell', index:12},
	];

  constructor(
    private _fournisseurService: FournisseurService,
    private _router: Router,
    private _notificationService: NotificationService,
    public dialog: MatDialog,
	private _route: ActivatedRoute) { }

  ngOnInit() {
    // On init get all Fournisseurs
    //this.getAllFournisseurs();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Fournisseur list
    EmitterService.get(this.listId).subscribe((data: Fournisseur[]) => this.getAllFournisseurs());
  }

  ngOnChanges() { }


  /**
   * Get displayed columns (responsive)
   */
  getDisplayedColumns(): string[] {
	  const isMobile = ApplicationStateService.getIsMobileResolution();
	  return this.columnDefinitions
	    .filter(cd => !isMobile || cd.showMobile)
	    .map(cd => cd.def);
	}

  /**
   * Get all Fournisseur using the service FournisseurService
   */
  getAllFournisseurs = (): void => {

	var options:any = { notPaged: true };
	
	if (this.filter) {
		if (this.filter == 'FULL') {
			options = { notPaged: true };
		}
		else {
			var filters = JSON.parse(this.filter);
			options = {params: filters,
						   notPaged: true};
		}

    	this._fournisseurService.getAll(options).subscribe(
      		(data: Fournisseur[]) => {
        		this.listOfFournisseurs = data;
      		},
      	error => {
        	this._notificationService.error(
          	'Error',
          	'An error occured when trying to reach the server');
    	});
	}
  }

  editFournisseur = (fournisseurid): void => {
    // Navigate to fournisseur form component
    this.goToFournisseurForm(fournisseurid);
  }

  deleteFournisseur = (fournisseurid): void => {

    const promise = new Promise((resolve, reject) => {
		// Call get service
		this._fournisseurService.get(fournisseurid).subscribe(
        		(fournisseur: Fournisseur) => {
          							this.fournisseur = fournisseur;
          							resolve('done');
        						},
				error => {
          					this._notificationService.error(error.statusText, 'Error delete');
            				reject('error');
        				 });
	})
    .then(() => {
    	// Call delete service
    	this._fournisseurService.delete(this.fournisseur).subscribe(
      			result => {
       						 // Notify Fournisseur list to refresh
        					EmitterService.get(this.listId).emit(result);

        					this._notificationService.success(
          					'Deleted',
          					`The fournisseur entry with the id='${fournisseurid}' was deleted successfuly`);
     					  },
      			error => {
        					this._notificationService.error(
          					'Error',
          					'An error occured when trying to reach the server');
      					  });
  	})
  }

  goToFournisseurForm(fournisseurid) {
    this._router.navigate(['./fournisseur-form', fournisseurid]);
  }

  deleteConfirmation = (fournisseurid) => {
    const dialogRef = this.dialog.open(DeleteDialogComponent, {
      data: `fournisseur: ${fournisseurid}`
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteFournisseur(fournisseurid);
      }
    });
  }

}
