// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:32 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Periode } from '../periode.model';

@Injectable()
export class PeriodeService extends RestService<Periode>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Periode, 'periode', injector);
    }

}
