// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:18 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Conge } from '../conge.model';

@Injectable()
export class CongeService extends RestService<Conge>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Conge, 'conge', injector);
    }

}
