// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:18 )


import { Resource } from 'angular4-hal';

export class Conge extends Resource {
	congeid: number; // Wrapper Type : Number
	idconsultant: number; // Wrapper Type : Number
	codeexercice: string; // Wrapper Type : String
	datedebut: Date; // Wrapper Type : Date
	datefin: Date; // Wrapper Type : Date
	commentaire: string; // Wrapper Type : String
	statut: string; // Wrapper Type : String
	nbj: number; // Wrapper Type : Number
	autorisationClient: boolean; // Wrapper Type : Boolean
	dateconsultant: Date; // Wrapper Type : Date
	dateprerequis: Date; // Wrapper Type : Date
	quiprerequis: number; // Wrapper Type : Number
}
