// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:17 )


import { Resource } from 'angular4-hal';

export class Client extends Resource {
	clientid: number; // Wrapper Type : Number
	raisonsociale: string; // Wrapper Type : String
	adresse1: string; // Wrapper Type : String
	adresse2: string; // Wrapper Type : String
	contact1: string; // Wrapper Type : String
	tel1Portable: string; // Wrapper Type : String
	tel1Travail: string; // Wrapper Type : String
	tel1Domicile: string; // Wrapper Type : String
	contact2: string; // Wrapper Type : String
	tel2Portable: string; // Wrapper Type : String
	tel2Travail: string; // Wrapper Type : String
	tel2Domicile: string; // Wrapper Type : String
	trigramme: string; // Wrapper Type : String
}
