// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:21 )


import { Resource } from 'angular4-hal';

export class Contratfournisseur extends Resource {
	contratfournisseurid: number; // Wrapper Type : Number
	reference: string; // Wrapper Type : String
	idfournisseur: number; // Wrapper Type : Number
	contact1: string; // Wrapper Type : String
	tel1Portable: string; // Wrapper Type : String
	tel1Travail: string; // Wrapper Type : String
	tel1Domicile: string; // Wrapper Type : String
	datedebut: Date; // Wrapper Type : Date
	datefin: Date; // Wrapper Type : Date
	referencefournisseur: string; // Wrapper Type : String
	avenant: string; // Wrapper Type : String
	mail1: string; // Wrapper Type : String
	adressefact: string; // Wrapper Type : String
	contactfact: string; // Wrapper Type : String
	categorie: string; // Wrapper Type : String
	factcra: boolean; // Wrapper Type : Boolean
	dateenvoi: Date; // Wrapper Type : Date
	dateretour: Date; // Wrapper Type : Date
	arcurssaf: string; // Wrapper Type : String
}
