// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:36 )

// Modules imports
import { NotificationService } from './../../../services/notification.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material';
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Models and services imports
import { Listeattr } from './../listeattr.model';
import { ListeattrService } from './../services/listeattr.service';
import * as _ from 'underscore';

// Pour gestion des listes
import { ListeService } from './../../../entities/liste/services/liste.service';
import { Liste } from './../../../entities/liste/liste.model';

import { Lov } from './../../../common/lov';
import {SelectItem} from 'primeng/api';

@Component({
  selector: 'app-listeattr-form',
  templateUrl: './listeattr-form.component.html',
  styleUrls: ['./listeattr-form.component.css'],
  providers: [DatePipe]
})
export class ListeattrFormComponent extends Lov implements OnInit {

  // HTTP status code
  readonly NOT_FOUND_ERROR = 404;
  readonly CONFLICT_ERROR = 409;
  readonly INTERNAL_SERVER_ERROR = 500;

  public title = 'Formulaire Listeattr';
  public form: FormGroup;

  // Définition des filtres

  public listeattr: Listeattr;
  private ids;

  // Définition des LOV

  constructor(
	private _listeService: ListeService,         // Pour gestion des listes
    private _listeattrService: ListeattrService,
    private _route: ActivatedRoute,
    private _router: Router,
    private _formBuilder: FormBuilder,
    private _notificationService: NotificationService,
    public dialog: MatDialog) {
		super(_listeService,_notificationService);
 	}

  ngOnInit() {
    this.getIdFromRouteParams();
    this.initForm();
  }

  getIdFromRouteParams = () => {
    this._route.params.subscribe(p => {
        this.ids = _.values(p);
    });
  }

  initForm = () => {
    this.form = this._formBuilder.group(this.getNewForm());
    if (!_.isEmpty(this.ids)) {
      this.load();
    }

	/* Chargement des LOVs */
  }

  getNewForm = (listeattr?: Listeattr) => {
    return {
      nomliste: [
          (listeattr ? listeattr.nomliste : ''),
          Validators.required
      ],
      codeelement: [
          (listeattr ? listeattr.codeelement : ''),
          Validators.required
      ],
      nomattribut: [
          (listeattr ? listeattr.nomattribut : ''),
          Validators.required
      ],
      valattribut: [
        (listeattr ? listeattr.valattribut : '')
      ]
    };
  }


  load = () => {
	// Concaténer les ids mais séparé par / et non ,
	var param : String = '';
	
	for (var i=0;i<this.ids.length;i++) {
		param = param + this.ids[i];
		if (i != (this.ids.length-1)) {
			param = param + '/';
		}
	}
    this._listeattrService.get(param).subscribe(
      (listeattr: Listeattr) => {
        this.listeattr = listeattr;
        this.form = this._formBuilder.group(this.getNewForm(this.listeattr));
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
 	  },
      () => {
		// Valorisation des filtres
      });
  }

  save = () => {
	// If we didn't get a listeattr, we are adding a listeattr
    if (!this.listeattr) {
      this.add();
    } else { // If we didn't get a listeattr, we are adding a listeattr
      this.update();
    }
  }

  add = () => {
    this._listeattrService.create(this.form.value).subscribe(
      result => {
        this._notificationService.success('Success', 'Listeattr added successfuly');
        this._router.navigate(['./listeattr-form', this.form.value.nomliste, this.form.value.codeelement, this.form.value.nomattribut]);
      },
      error => {1
        if (error.status === this.CONFLICT_ERROR) {
          this._notificationService.error(error.statusText, 'Id already used in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  update = () => {
	Object.assign(this.listeattr,this.form.value);
    this._listeattrService.update(this.listeattr).subscribe(
      result => this._notificationService.success('Success', 'Listeattr edited successfuly'),
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  deleteConfirmation = () => {
    if (this.listeattr.nomliste && this.listeattr.codeelement && this.listeattr.nomattribut) {
      const dialogRef = this.dialog.open(DeleteDialogComponent, {
        data: `listeattr: ${this.listeattr.nomliste}, ${this.listeattr.codeelement}, ${this.listeattr.nomattribut}`
      });
      dialogRef.afterClosed().subscribe(result => {
        if (result) {
          this.deleteBadge(this.listeattr);
        }
      });
    }
  }

  deleteBadge = (listeattr: Listeattr): void => {
    // Call delete service
    this._listeattrService.delete(listeattr).subscribe(
      result => {
        this._router.navigate(['./listeattr-list']);

        this._notificationService.success(
          'Deleted',
         // `The listeattr entry with the id(s)='${nomliste}, ${codeelement}, ${nomattribut}' was deleted successfuly`);
 		`The listeattr entry with the id= was deleted successfuly`);
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }
}
