// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:34 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Liencontrat } from '../liencontrat.model';

@Injectable()
export class LiencontratService extends RestService<Liencontrat>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Liencontrat, 'liencontrat', injector);
    }

}
