// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-01-20 ( Time 14:01:01 )

import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-not-found',
  templateUrl: './not-found.component.html',
  styleUrls: ['./not-found.component.css']
})
export class NotFoundComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
