// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:17 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Client } from '../client.model';

@Injectable()
export class ClientService extends RestService<Client>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Client, 'client', injector);
    }

}
