// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-01-20 ( Time 14:01:01 )

import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css']
})
export class AboutComponent implements OnInit {

  title: String = 'About';

  constructor() {
   }

  ngOnInit() {
  }

}
