// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-01-20 ( Time 14:01:01 )

import { Component, OnInit } from '@angular/core';
import {SelectItem} from 'primeng/api';

interface City {
  name: string;
  code: string;
}

interface City_itm {
  id : number;
  name: string;
  code: string;
}

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css']
})
export class AboutComponent implements OnInit {

  title: String = 'About';

    cities1: SelectItem[];
    cities2: City[];
    selectedCity1: City_itm;
    selectedCity2: City;
	selectedCity3: Object;// Obligé de mettre object
	cities3: SelectItem[]; 
  constructor() {
	//SelectItem API with label-value pairs
        this.cities1 = [
            {label:'Select City', value:null},
            {label:'New York', value:{id:1, name: 'New York', code: 'NY'}},
            {label:'Rome', value:{id:2, name: 'Rome', code: 'RM'}},
            {label:'London', value:{id:3, name: 'London', code: 'LDN'}},
            {label:'Istanbul', value:{id:4, name: 'Istanbul', code: 'IST'}},
            {label:'Paris', value:{id:5, name: 'Paris', code: 'PRS'}}
        ];

		this.selectedCity1 ={id:2, name: 'Rome', code: 'RM'};
		
        //An array of cities
        this.cities2 = [
            {name: 'New York', code: 'NY'},
            {name: 'Rome', code: 'RM'},
            {name: 'London', code: 'LDN'},
            {name: 'Istanbul', code: 'IST'},
            {name: 'Paris', code: 'PRS'}
        ];
		this.selectedCity2 = {name: 'Istanbul', code: 'IST'};
		
		this.cities3 = [];
		// transformer cities2 en cities3
		 this.cities2.forEach((c, index) => {
			console.log((index+1) + ' ' + c.code + ' - ' + c.name);
			this.cities3.push({label:c.code + ' - ' + c.name, value:{id:index + 1, ...c}});
		    });

		this.selectedCity3 = { id:3 ,name: 'London', code: 'LDN'};
		
   }

  ngOnInit() {
  }

}
	