// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 16:11:46 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-rubriquefrais-listheader',
  templateUrl: './rubriquefrais-listheader.component.html',
  styleUrls: ['./rubriquefrais-listheader.component.css'],
  providers: []
})
export class RubriquefraisListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Rubriquefraiss';
  public filter:string = 'FULL';

  private columnDefinitions = [
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
