// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 16:11:45 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';
import { Router } from '@angular/router';
import { ActivatedRoute  } from '@angular/router';
import { MatDialog } from '@angular/material';

// Services imports
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { RubriquefraisService } from './../services/rubriquefrais.service';
import { ApplicationStateService } from './../../../services/application-state.service';

// Models imports
import { Rubriquefrais } from '../rubriquefrais.model';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Ajout primeng
import {TableModule} from 'primeng/table';
import {PaginatorModule} from 'primeng/paginator';

@Component({
  selector: 'app-rubriquefrais-list',
  templateUrl: './rubriquefrais-list.component.html',
  styleUrls: ['./rubriquefrais-list.component.css'],
  providers: [DatePipe]
})
export class RubriquefraisListComponent implements OnInit, OnChanges {

  public title = 'Liste de Rubriquefraiss';

  public listOfRubriquefraiss: Rubriquefrais[];


  _filter : string;
  @Input('filter') 
  set filter(value:string) {
	 this._filter = value;
     this.getAllRubriquefraiss();
  }

  get filter():string {
	return this._filter
  }

  @Input() createenable?: boolean = true;
  @Input() deleteenable?: boolean = true;
  @Input() updateenable?: boolean = true;
  @Input() incard?: boolean = true;

  private listId = 'RUBRIQUEFRAIS_COMPONENT_LIST';

  private rubriquefrais: Rubriquefrais;

  private columnDefinitions = [
      { def: 'code', showMobile: true, display:'none', index:0},
      { def: 'nom', showMobile: true, display:'none', index:1},
      { def: 'ordre', showMobile: true, display:'none', index:2},
      { def: 'ccstructure', showMobile: true, display:'none', index:3},
      { def: 'cccommercial', showMobile: true, display:'none', index:4},
      { def: 'ccoperationnel', showMobile: true, display:'none', index:5},
      { def: 'ccrefact', showMobile: true, display:'none', index:6},
      { def: 'image', showMobile: true, display:'none', index:7},
	];

  constructor(
    private _rubriquefraisService: RubriquefraisService,
    private _router: Router,
    private _notificationService: NotificationService,
    public dialog: MatDialog,
	private _route: ActivatedRoute) { }

  ngOnInit() {
    // On init get all Rubriquefraiss
    //this.getAllRubriquefraiss();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Rubriquefrais list
    EmitterService.get(this.listId).subscribe((data: Rubriquefrais[]) => this.getAllRubriquefraiss());
  }

  ngOnChanges() { }


  /**
   * Get displayed columns (responsive)
   */
  getDisplayedColumns(): string[] {
	  const isMobile = ApplicationStateService.getIsMobileResolution();
	  return this.columnDefinitions
	    .filter(cd => !isMobile || cd.showMobile)
	    .map(cd => cd.def);
	}

  /**
   * Get all Rubriquefrais using the service RubriquefraisService
   */
  getAllRubriquefraiss = (): void => {

	var options:any = { notPaged: true };
	
	if (this.filter) {
		if (this.filter == 'FULL') {
			options = { notPaged: true };
		}
		else {
			var filters = JSON.parse(this.filter);
			options = {params: filters,
						   notPaged: true};
		}

    	this._rubriquefraisService.getAll(options).subscribe(
      		(data: Rubriquefrais[]) => {
        		this.listOfRubriquefraiss = data;
      		},
      	error => {
        	this._notificationService.error(
          	'Error',
          	'An error occured when trying to reach the server');
    	});
	}
  }

  editRubriquefrais = (code): void => {
    // Navigate to rubriquefrais form component
    this.goToRubriquefraisForm(code);
  }

  deleteRubriquefrais = (code): void => {

    const promise = new Promise((resolve, reject) => {
		// Call get service
		this._rubriquefraisService.get([code]).subscribe(
        		(rubriquefrais: Rubriquefrais) => {
          							this.rubriquefrais = rubriquefrais;
          							resolve('done');
        						},
				error => {
          					this._notificationService.error(error.statusText, 'Error delete');
            				reject('error');
        				 });
	})
    .then(() => {
    	// Call delete service
    	this._rubriquefraisService.delete(this.rubriquefrais).subscribe(
      			result => {
       						 // Notify Rubriquefrais list to refresh
        					EmitterService.get(this.listId).emit(result);

        					this._notificationService.success(
          					'Deleted',
          					`The rubriquefrais entry with the id='${code}' was deleted successfuly`);
     					  },
      			error => {
        					this._notificationService.error(
          					'Error',
          					'An error occured when trying to reach the server');
      					  });
  	})
  }

  goToRubriquefraisForm(code) {
    this._router.navigate(['./rubriquefrais-form', code]);
  }

  deleteConfirmation = (code) => {
    const dialogRef = this.dialog.open(DeleteDialogComponent, {
      data: `rubriquefrais: ${code}`
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteRubriquefrais(code);
      }
    });
  }

}
