// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:33 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-postebudgetaire-listheader',
  templateUrl: './postebudgetaire-listheader.component.html',
  styleUrls: ['./postebudgetaire-listheader.component.css'],
  providers: []
})
export class PostebudgetaireListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Postebudgetaires';
  public filter:string = 'FULL';

  private columnDefinitions = [
      { def: 'code', showMobile: true },
      { def: 'nom', showMobile: true },
      { def: 'ordre', showMobile: true },
      { def: 'analytique', showMobile: true },
      { def: 'image', showMobile: true },
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
