// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-14 ( Time 19:36:40 )


import { Resource } from 'angular4-hal';

export class Calendrier extends Resource {
	datecalendrier: Date; // Wrapper Type : Date
	codeperiode: string; // Wrapper Type : String
	ferie: string; // Wrapper Type : String
}
