// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-23 ( Time 12:51:49 )


import { Resource } from 'angular4-hal';

export class Calendrier extends Resource {
	datecalendrier: Date; // Wrapper Type : Date
	codeperiode: string; // Wrapper Type : String
	ferie: boolean; // Wrapper Type : Boolean
}
