// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:36 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Listeattr } from '../listeattr.model';

@Injectable()
export class ListeattrService extends RestService<Listeattr>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Listeattr, 'listeattr', injector);
    }

}
