// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:14 )


import { Resource } from 'angular4-hal';

export class Alerte extends Resource {
	code: string; // Wrapper Type : String
	description: string; // Wrapper Type : String
	email: string; // Wrapper Type : String
}
