// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-02-20 ( Time 13:54:32 )


import { Resource } from 'angular4-hal';

export class Consultant extends Resource {
	consultantid: number; // Wrapper Type : Number
	nom: string; // Wrapper Type : String
	prenom: string; // Wrapper Type : String
	trigramme: string; // Wrapper Type : String
	userLogin: string; // Wrapper Type : String
	userPassword: string; // Wrapper Type : String
	adresse1: string; // Wrapper Type : String
	adresse2: string; // Wrapper Type : String
	telPortable: string; // Wrapper Type : String
	telTravail: string; // Wrapper Type : String
	telDomicile: string; // Wrapper Type : String
	codeprofil: string; // Wrapper Type : String
	datefin: Date; // Wrapper Type : Date
	email: string; // Wrapper Type : String
	datedebut: Date; // Wrapper Type : Date
	codepostal: string; // Wrapper Type : String
	ville: string; // Wrapper Type : String
	lieunaissance: string; // Wrapper Type : String
	datenaissance: Date; // Wrapper Type : Date
	telimei: string; // Wrapper Type : String
	telcontrat: string; // Wrapper Type : String
	telecheance: Date; // Wrapper Type : Date
	vehpersimmat: string; // Wrapper Type : String
	vehproimmat: string; // Wrapper Type : String
	vehproass: string; // Wrapper Type : String
	vehperscv: number; // Wrapper Type : Number
	vehprocv: number; // Wrapper Type : Number
	vehpermis: string; // Wrapper Type : String
	vehpersmodele: string; // Wrapper Type : String
	vehpromodele: string; // Wrapper Type : String
	vehprorevision: string; // Wrapper Type : String
	vehprotauxspec: number; // Wrapper Type : Number
	ordmodele: string; // Wrapper Type : String
	orddate: Date; // Wrapper Type : Date
	ordmontantht: number; // Wrapper Type : Number
	ordinfo: string; // Wrapper Type : String
	adslplaf: number; // Wrapper Type : Number
	telpersplaf: number; // Wrapper Type : Number
	trspkmsiege: boolean; // Wrapper Type : Boolean
	trspnbkmsiege: number; // Wrapper Type : Number
	trspcarte: number; // Wrapper Type : Number
	societe: string; // Wrapper Type : String
	comptendf: string; // Wrapper Type : String
}
