// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:24 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';
import { Router } from '@angular/router';
import { ActivatedRoute  } from '@angular/router';
import { MatDialog } from '@angular/material';

// Services imports
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { EcheancecontratService } from './../services/echeancecontrat.service';
import { ApplicationStateService } from './../../../services/application-state.service';

// Models imports
import { Echeancecontrat } from '../echeancecontrat.model';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Ajout primeng
import {TableModule} from 'primeng/table';
import {PaginatorModule} from 'primeng/paginator';

@Component({
  selector: 'app-echeancecontrat-list',
  templateUrl: './echeancecontrat-list.component.html',
  styleUrls: ['./echeancecontrat-list.component.css'],
  providers: [DatePipe]
})
export class EcheancecontratListComponent implements OnInit, OnChanges {

  public title = 'Liste de Echeancecontrats';

  public listOfEcheancecontrats: Echeancecontrat[];


  _filter : string;
  @Input('filter') 
  set filter(value:string) {
	 this._filter = value;
     this.getAllEcheancecontrats();
  }

  get filter():string {
	return this._filter
  }

  @Input() createenable?: boolean = true;
  @Input() deleteenable?: boolean = true;
  @Input() updateenable?: boolean = true;
  @Input() incard?: boolean = true;

  private listId = 'ECHEANCECONTRAT_COMPONENT_LIST';

  private echeancecontrat: Echeancecontrat;

  private columnDefinitions = [
      { def: 'montantht', showMobile: true, display:'none', index:0},
      { def: 'tauxtva', showMobile: true, display:'none', index:1},
      { def: 'echeancecontratid', showMobile: true, display:'table-cell', index:2},
      { def: 'idcontrat', showMobile: true, display:'table-cell', index:3},
      { def: 'dateecheance', showMobile: true, display:'table-cell', index:4},
      { def: 'libelle', showMobile: true, display:'table-cell', index:5},
	];

  constructor(
    private _echeancecontratService: EcheancecontratService,
    private _router: Router,
    private _notificationService: NotificationService,
    public dialog: MatDialog,
	private _route: ActivatedRoute) { }

  ngOnInit() {
    // On init get all Echeancecontrats
    //this.getAllEcheancecontrats();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Echeancecontrat list
    EmitterService.get(this.listId).subscribe((data: Echeancecontrat[]) => this.getAllEcheancecontrats());
  }

  ngOnChanges() { }


  /**
   * Get displayed columns (responsive)
   */
  getDisplayedColumns(): string[] {
	  const isMobile = ApplicationStateService.getIsMobileResolution();
	  return this.columnDefinitions
	    .filter(cd => !isMobile || cd.showMobile)
	    .map(cd => cd.def);
	}

  /**
   * Get all Echeancecontrat using the service EcheancecontratService
   */
  getAllEcheancecontrats = (): void => {

	var options:any = { notPaged: true };
	
	if (this.filter) {
		if (this.filter == 'FULL') {
			options = { notPaged: true };
		}
		else {
			var filters = JSON.parse(this.filter);
			options = {params: filters,
						   notPaged: true};
		}

    	this._echeancecontratService.getAll(options).subscribe(
      		(data: Echeancecontrat[]) => {
        		this.listOfEcheancecontrats = data;
      		},
      	error => {
        	this._notificationService.error(
          	'Error',
          	'An error occured when trying to reach the server');
    	});
	}
  }

  editEcheancecontrat = (echeancecontratid): void => {
    // Navigate to echeancecontrat form component
    this.goToEcheancecontratForm(echeancecontratid);
  }

  deleteEcheancecontrat = (echeancecontratid): void => {

    const promise = new Promise((resolve, reject) => {
		// Call get service
		this._echeancecontratService.get(echeancecontratid).subscribe(
        		(echeancecontrat: Echeancecontrat) => {
          							this.echeancecontrat = echeancecontrat;
          							resolve('done');
        						},
				error => {
          					this._notificationService.error(error.statusText, 'Error delete');
            				reject('error');
        				 });
	})
    .then(() => {
    	// Call delete service
    	this._echeancecontratService.delete(this.echeancecontrat).subscribe(
      			result => {
       						 // Notify Echeancecontrat list to refresh
        					EmitterService.get(this.listId).emit(result);

        					this._notificationService.success(
          					'Deleted',
          					`The echeancecontrat entry with the id='${echeancecontratid}' was deleted successfuly`);
     					  },
      			error => {
        					this._notificationService.error(
          					'Error',
          					'An error occured when trying to reach the server');
      					  });
  	})
  }

  goToEcheancecontratForm(echeancecontratid) {
    this._router.navigate(['./echeancecontrat-form', echeancecontratid]);
  }

  deleteConfirmation = (echeancecontratid) => {
    const dialogRef = this.dialog.open(DeleteDialogComponent, {
      data: `echeancecontrat: ${echeancecontratid}`
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteEcheancecontrat(echeancecontratid);
      }
    });
  }

}
