// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-05-04 ( Time 16:33:23 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Baremekm } from '../baremekm.model';
import { Observable } from 'rxjs/observable';

@Injectable()
export class BaremekmService extends RestService<Baremekm>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Baremekm, 'baremekm', injector);
    }

}
