// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:18 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Baremekm } from '../baremekm.model';

@Injectable()
export class BaremekmService extends RestService<Baremekm>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Baremekm, 'baremekm', injector);
    }

}
