// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-01-20 ( Time 13:33:09 )

import { Router, RouterModule } from '@angular/router';
import { NotFoundComponent } from './not-found/not-found.component';
import { AboutComponent } from './about/about.component';
import { HomeListComponent } from './home-list/home-list.component';
import { LoginComponent } from './login/login.component';

// Menu
import { MenuListComponent } from './entities/menu/menu-list/menu-list.component';
import { MenuFormComponent } from './entities/menu/menu-form/menu-form.component';

// Menu
import { ConsultantListComponent } from './entities/consultant/consultant-list/consultant-list.component';
import { ConsultantFormComponent } from './entities/consultant/consultant-form/consultant-form.component';

import { AuthGuard } from './auth.guard';

export const AppRouting = RouterModule.forRoot([
    { path: '', component: HomeListComponent },
    // { canActivate : [AuthGuard],
    //  children: [
        { path: 'menu-list', component: MenuListComponent , canActivate : [AuthGuard]},
        { path: 'menu-form/:id', component: MenuFormComponent , canActivate : [AuthGuard]},
        { path: 'menu-form', component: MenuFormComponent , canActivate : [AuthGuard]},
        { path: 'consultant-list', component: ConsultantListComponent , canActivate : [AuthGuard]},
        { path: 'consultant-form/:id', component: ConsultantFormComponent , canActivate : [AuthGuard]},
        { path: 'consultant-form', component: ConsultantFormComponent , canActivate : [AuthGuard]},
        { path: 'deconnect', component: LoginComponent },
        { path: 'about', component: AboutComponent },
        { path: '**', component: NotFoundComponent }
    // ]}
]);
