// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-20 ( Time 13:36:06 )

import { Router, RouterModule } from '@angular/router';
import { NotFoundComponent } from './not-found/not-found.component';
import { AboutComponent } from './about/about.component';
import { HomeListComponent } from './home-list/home-list.component';
import { LoginComponent } from './login/login.component';

import { AuthGuard } from './auth.guard';

// Calendrier
import { CalendrierListheaderComponent } from './entities/calendrier/calendrier-list/calendrier-listheader.component';
import { CalendrierListComponent } from './entities/calendrier/calendrier-list/calendrier-list.component';
import { CalendrierFormComponent } from './entities/calendrier/calendrier-form/calendrier-form.component';

// Consultant
import { ConsultantListheaderComponent } from './entities/consultant/consultant-list/consultant-listheader.component';
import { ConsultantListComponent } from './entities/consultant/consultant-list/consultant-list.component';
import { ConsultantFormComponent } from './entities/consultant/consultant-form/consultant-form.component';

// Fournisseur
import { FournisseurListheaderComponent } from './entities/fournisseur/fournisseur-list/fournisseur-listheader.component';
import { FournisseurListComponent } from './entities/fournisseur/fournisseur-list/fournisseur-list.component';
import { FournisseurFormComponent } from './entities/fournisseur/fournisseur-form/fournisseur-form.component';

// Liste
import { ListeListheaderComponent } from './entities/liste/liste-list/liste-listheader.component';
import { ListeListComponent } from './entities/liste/liste-list/liste-list.component';
import { ListeFormComponent } from './entities/liste/liste-form/liste-form.component';

// Menu
import { MenuListheaderComponent } from './entities/menu/menu-list/menu-listheader.component';
import { MenuListComponent } from './entities/menu/menu-list/menu-list.component';
import { MenuFormComponent } from './entities/menu/menu-form/menu-form.component';

// Periode
import { PeriodeListheaderComponent } from './entities/periode/periode-list/periode-listheader.component';
import { PeriodeListComponent } from './entities/periode/periode-list/periode-list.component';
import { PeriodeFormComponent } from './entities/periode/periode-form/periode-form.component';

// Exercice
import { ExerciceListheaderComponent } from './entities/exercice/exercice-list/exercice-listheader.component';
import { ExerciceListComponent } from './entities/exercice/exercice-list/exercice-list.component';
import { ExerciceFormComponent } from './entities/exercice/exercice-form/exercice-form.component';

export const AppRouting = RouterModule.forRoot([
    { path: '', 
      //component: HomeListComponent
      redirectTo: 'login',
      pathMatch: 'full' 
    },
    // { canActivate : [AuthGuard],
    //  children: [
        { path: 'calendrier-list', component: CalendrierListheaderComponent, canActivate : [AuthGuard]},
        { path: 'calendrier-form/:id', component: CalendrierFormComponent, canActivate : [AuthGuard] },
        { path: 'calendrier-form', component: CalendrierFormComponent, canActivate : [AuthGuard] },
        { path: 'consultant-list', component: ConsultantListheaderComponent, canActivate : [AuthGuard]},
        { path: 'consultant-form/:id', component: ConsultantFormComponent, canActivate : [AuthGuard] },
        { path: 'consultant-form', component: ConsultantFormComponent, canActivate : [AuthGuard] },
        { path: 'fournisseur-list', component: FournisseurListheaderComponent, canActivate : [AuthGuard]},
        { path: 'fournisseur-form/:id', component: FournisseurFormComponent, canActivate : [AuthGuard] },
        { path: 'fournisseur-form', component: FournisseurFormComponent, canActivate : [AuthGuard] },
        { path: 'liste-list', component: ListeListheaderComponent, canActivate : [AuthGuard]},
        { path: 'liste-form/:id1/:id2', component: ListeFormComponent, canActivate : [AuthGuard] },
        { path: 'liste-form', component: ListeFormComponent, canActivate : [AuthGuard] },
        { path: 'menu-list', component: MenuListheaderComponent, canActivate : [AuthGuard]},
        { path: 'menu-form/:id', component: MenuFormComponent, canActivate : [AuthGuard] },
        { path: 'menu-form', component: MenuFormComponent, canActivate : [AuthGuard] },
        { path: 'periode-list', component: PeriodeListheaderComponent, canActivate : [AuthGuard]},
        { path: 'periode-form/:id', component: PeriodeFormComponent, canActivate : [AuthGuard] },
        { path: 'periode-form', component: PeriodeFormComponent, canActivate : [AuthGuard] },
        { path: 'exercice-list', component: ExerciceListheaderComponent, canActivate : [AuthGuard]},
        { path: 'exercice-form/:id', component: ExerciceFormComponent, canActivate : [AuthGuard] },
        { path: 'exercice-form', component: ExerciceFormComponent, canActivate : [AuthGuard] },
        { path: 'deconnect', component: LoginComponent },
        { path: 'about', component: AboutComponent },
    { path: '**',
      redirectTo: 'login',
      //component: NotFoundComponent 
    }
]);