// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-01-20 ( Time 13:33:09 )

import { BrowserModule } from '@angular/platform-browser';
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { AppComponent } from './app.component';
import { HttpClientModule } from '@angular/common/http';

// Routing
import { AppRouting } from './app.routing';

// Menu Components
import { MenuListComponent } from './entities/menu/menu-list/menu-list.component';
import { MenuFormComponent } from './entities/menu/menu-form/menu-form.component';

// Consultant Components
import { ConsultantListComponent } from './entities/consultant/consultant-list/consultant-list.component';
import { ConsultantFormComponent } from './entities/consultant/consultant-form/consultant-form.component';

// Liste Components
import { ListeListComponent } from './entities/liste/liste-list/liste-list.component';
import { ListeFormComponent } from './entities/liste/liste-form/liste-form.component';

// Other Components
import { NotFoundComponent } from './not-found/not-found.component';
import { AboutComponent } from './about/about.component';
import { DeleteDialogComponent } from './delete-dialog/delete-dialog.component';
import { HomeListComponent } from './home-list/home-list.component';

// Modules
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { SimpleNotificationsModule } from 'angular2-notifications';

import {MatDatepickerModule} from '@angular/material/datepicker';

import { MaterialModule} from './material-module'

// Services
import { MenuService } from './entities/menu/services/menu.service';
import { ConsultantService } from './entities/consultant/services/consultant.service';
import { ListeService } from './entities/liste/services/liste.service';


import { EmitterService } from './services/emitter.service';
import { NotificationService } from './services/notification.service';
// import { PagerService } from './services/pager.service';

import { ApplicationStateService } from './services/application-state.service';

import {AngularHalModule} from 'angular4-hal';
import {ExternalConfigurationService} from './ExternalConfigurationService';

//import { DatePipe } from '@angular/common';
import { DateAdapter, MAT_DATE_LOCALE } from '@angular/material/core';
import { MatMomentDateModule, MAT_MOMENT_DATE_ADAPTER_OPTIONS } from '@angular/material-moment-adapter';
// import { PickDateAdapter, PICK_FORMATS } from './adapter/pickdate.adapter';
import { PlatformModule} from '@angular/cdk/platform';

import { registerLocaleData } from '@angular/common';
import localeFr from '@angular/common/locales/fr';
import localeFrExtra from '@angular/common/locales/extra/fr';
// import TranslateModule from  '@ngx-translate/core';

import { AuthGuard } from './auth.guard';
import { LoginComponent } from './login/login.component';
import { LoginRoutingModule } from './login/login.routing';

import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { AngularDateHttpInterceptor } from './interceptors/AngularDateHttp.interceptor';

import {WebStorageModule, LocalStorageService} from "angular-localstorage";

import {FlexLayoutModule} from '@angular/flex-layout';
// import {NgbModule} from '@ng-bootstrap/ng-bootstrap';

registerLocaleData(localeFr, 'fr-FR', localeFrExtra);

@NgModule({
  declarations: [
    AppComponent,
    MenuListComponent,
    MenuFormComponent,
    ConsultantListComponent,
    ConsultantFormComponent,
    ListeListComponent,
    ListeFormComponent,
    NotFoundComponent,
    AboutComponent,
    DeleteDialogComponent,
    HomeListComponent,
    LoginComponent
],
  entryComponents: [
    DeleteDialogComponent
],
  imports: [
    BrowserModule,
    CommonModule,
    ReactiveFormsModule,
    HttpClientModule,
    LoginRoutingModule, // doit être avant AppRouting
    AppRouting,
    BrowserAnimationsModule,
	MaterialModule,
    MatDatepickerModule,
    PlatformModule,
    SimpleNotificationsModule.forRoot(),
    AngularHalModule.forRoot(),
    MatMomentDateModule, // permet de gérer la timezone
    FlexLayoutModule,
],
  providers: [
    { provide: 'ExternalConfigurationService', useClass: ExternalConfigurationService },
    { provide: MAT_DATE_LOCALE, useValue: 'fr-FR' },
    { provide: MAT_MOMENT_DATE_ADAPTER_OPTIONS, useValue: { useUtc: true } },
    ConsultantService,
    MenuService,
	ListeService,
    EmitterService,
    NotificationService,
	ApplicationStateService,
    MatDatepickerModule,
    AuthGuard,
    {
      provide: HTTP_INTERCEPTORS,
      useClass: AngularDateHttpInterceptor,
      multi: true
    },
    // LocalStorageService
    // DatePipe
],
  bootstrap: [AppComponent]
})
export class AppModule {
     constructor(private dateAdapter: DateAdapter<Date>){
       dateAdapter.setLocale('fr-FR');
   }
 }
