// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-01-20 ( Time 13:33:09 )

import { NotificationService } from './services/notification.service';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {

  title: String = 'Home';

  public navigation = [
    { title: 'Menu', routerLink: 'menu-list' },
    { title: 'Consultant', routerLink: 'consultant-list' }
  ];

  public optionsForNotifications = {
    position: ['bottom', 'left'],
    timeOut: 5000,
    lastOnBottom: true,
    showProgressBar: false,
    pauseOnHover: false,
    clickToClose: true,
    preventDuplicates: true
  };

  constructor(
    private _notificationService: NotificationService) { }

  ngOnInit() {
    this._notificationService.init();
  }
}
