// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:25:28 )

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { CommonModule } from '@angular/common';

import { ReactiveFormsModule } from '@angular/forms';

import { AppComponent } from './app.component';
// Routing
import { AppRouting } from './app.routing';

import { HttpClientModule } from '@angular/common/http';

import { AppMenuComponent, AppSubMenuComponent} from './app.menu.component';
import { AppTopBarComponent } from './app.topbar.component';
import { AppFooterComponent } from './app.footer.component';
import { DashboardComponent } from './pages/dashboard.component';


// Alerte Components
import { AlerteListheaderComponent } from './entities/alerte/alerte-list/alerte-listheader.component';
import { AlerteListComponent } from './entities/alerte/alerte-list/alerte-list.component';
import { AlerteFormComponent } from './entities/alerte/alerte-form/alerte-form.component';

// Baremekm Components
import { BaremekmListheaderComponent } from './entities/baremekm/baremekm-list/baremekm-listheader.component';
import { BaremekmListComponent } from './entities/baremekm/baremekm-list/baremekm-list.component';
import { BaremekmFormComponent } from './entities/baremekm/baremekm-form/baremekm-form.component';

// Calendrier Components
import { CalendrierListheaderComponent } from './entities/calendrier/calendrier-list/calendrier-listheader.component';
import { CalendrierListComponent } from './entities/calendrier/calendrier-list/calendrier-list.component';
import { CalendrierFormComponent } from './entities/calendrier/calendrier-form/calendrier-form.component';

// Client Components
import { ClientListheaderComponent } from './entities/client/client-list/client-listheader.component';
import { ClientListComponent } from './entities/client/client-list/client-list.component';
import { ClientFormComponent } from './entities/client/client-form/client-form.component';

// Conge Components
import { CongeListheaderComponent } from './entities/conge/conge-list/conge-listheader.component';
import { CongeListComponent } from './entities/conge/conge-list/conge-list.component';
import { CongeFormComponent } from './entities/conge/conge-form/conge-form.component';

// Consultant Components
import { ConsultantListheaderComponent } from './entities/consultant/consultant-list/consultant-listheader.component';
import { ConsultantListComponent } from './entities/consultant/consultant-list/consultant-list.component';
import { ConsultantFormComponent } from './entities/consultant/consultant-form/consultant-form.component';

// Consultantcontrat Components
import { ConsultantcontratListheaderComponent } from './entities/consultantcontrat/consultantcontrat-list/consultantcontrat-listheader.component';
import { ConsultantcontratListComponent } from './entities/consultantcontrat/consultantcontrat-list/consultantcontrat-list.component';
import { ConsultantcontratFormComponent } from './entities/consultantcontrat/consultantcontrat-form/consultantcontrat-form.component';

// Consultantcontratfournisseur Components
import { ConsultantcontratfournisseurListheaderComponent } from './entities/consultantcontratfournisseur/consultantcontratfournisseur-list/consultantcontratfournisseur-listheader.component';
import { ConsultantcontratfournisseurListComponent } from './entities/consultantcontratfournisseur/consultantcontratfournisseur-list/consultantcontratfournisseur-list.component';
import { ConsultantcontratfournisseurFormComponent } from './entities/consultantcontratfournisseur/consultantcontratfournisseur-form/consultantcontratfournisseur-form.component';

// Contrat Components
import { ContratListheaderComponent } from './entities/contrat/contrat-list/contrat-listheader.component';
import { ContratListComponent } from './entities/contrat/contrat-list/contrat-list.component';
import { ContratFormComponent } from './entities/contrat/contrat-form/contrat-form.component';

// Contratfournisseur Components
import { ContratfournisseurListheaderComponent } from './entities/contratfournisseur/contratfournisseur-list/contratfournisseur-listheader.component';
import { ContratfournisseurListComponent } from './entities/contratfournisseur/contratfournisseur-list/contratfournisseur-list.component';
import { ContratfournisseurFormComponent } from './entities/contratfournisseur/contratfournisseur-form/contratfournisseur-form.component';

// Cra Components
import { CraListheaderComponent } from './entities/cra/cra-list/cra-listheader.component';
import { CraListComponent } from './entities/cra/cra-list/cra-list.component';
import { CraFormComponent } from './entities/cra/cra-form/cra-form.component';

// Document Components
import { DocumentListheaderComponent } from './entities/document/document-list/document-listheader.component';
import { DocumentListComponent } from './entities/document/document-list/document-list.component';
import { DocumentFormComponent } from './entities/document/document-form/document-form.component';

// Echeancecontrat Components
import { EcheancecontratListheaderComponent } from './entities/echeancecontrat/echeancecontrat-list/echeancecontrat-listheader.component';
import { EcheancecontratListComponent } from './entities/echeancecontrat/echeancecontrat-list/echeancecontrat-list.component';
import { EcheancecontratFormComponent } from './entities/echeancecontrat/echeancecontrat-form/echeancecontrat-form.component';

// Echeancecontratfournisseur Components
import { EcheancecontratfournisseurListheaderComponent } from './entities/echeancecontratfournisseur/echeancecontratfournisseur-list/echeancecontratfournisseur-listheader.component';
import { EcheancecontratfournisseurListComponent } from './entities/echeancecontratfournisseur/echeancecontratfournisseur-list/echeancecontratfournisseur-list.component';
import { EcheancecontratfournisseurFormComponent } from './entities/echeancecontratfournisseur/echeancecontratfournisseur-form/echeancecontratfournisseur-form.component';

// Exercice Components
import { ExerciceListheaderComponent } from './entities/exercice/exercice-list/exercice-listheader.component';
import { ExerciceListComponent } from './entities/exercice/exercice-list/exercice-list.component';
import { ExerciceFormComponent } from './entities/exercice/exercice-form/exercice-form.component';

// Fournisseur Components
import { FournisseurListheaderComponent } from './entities/fournisseur/fournisseur-list/fournisseur-listheader.component';
import { FournisseurListComponent } from './entities/fournisseur/fournisseur-list/fournisseur-list.component';
import { FournisseurFormComponent } from './entities/fournisseur/fournisseur-form/fournisseur-form.component';

// Frais Components
import { FraisListheaderComponent } from './entities/frais/frais-list/frais-listheader.component';
import { FraisListComponent } from './entities/frais/frais-list/frais-list.component';
import { FraisFormComponent } from './entities/frais/frais-form/frais-form.component';

// Fraiskmunit Components
import { FraiskmunitListheaderComponent } from './entities/fraiskmunit/fraiskmunit-list/fraiskmunit-listheader.component';
import { FraiskmunitListComponent } from './entities/fraiskmunit/fraiskmunit-list/fraiskmunit-list.component';
import { FraiskmunitFormComponent } from './entities/fraiskmunit/fraiskmunit-form/fraiskmunit-form.component';

// Fraisunit Components
import { FraisunitListheaderComponent } from './entities/fraisunit/fraisunit-list/fraisunit-listheader.component';
import { FraisunitListComponent } from './entities/fraisunit/fraisunit-list/fraisunit-list.component';
import { FraisunitFormComponent } from './entities/fraisunit/fraisunit-form/fraisunit-form.component';

// Liencontrat Components
import { LiencontratListheaderComponent } from './entities/liencontrat/liencontrat-list/liencontrat-listheader.component';
import { LiencontratListComponent } from './entities/liencontrat/liencontrat-list/liencontrat-list.component';
import { LiencontratFormComponent } from './entities/liencontrat/liencontrat-form/liencontrat-form.component';

// Liste Components
import { ListeListheaderComponent } from './entities/liste/liste-list/liste-listheader.component';
import { ListeListComponent } from './entities/liste/liste-list/liste-list.component';
import { ListeFormComponent } from './entities/liste/liste-form/liste-form.component';

// Menu Components
import { MenuListheaderComponent } from './entities/menu/menu-list/menu-listheader.component';
import { MenuListComponent } from './entities/menu/menu-list/menu-list.component';
import { MenuFormComponent } from './entities/menu/menu-form/menu-form.component';

// Periode Components
import { PeriodeListheaderComponent } from './entities/periode/periode-list/periode-listheader.component';
import { PeriodeListComponent } from './entities/periode/periode-list/periode-list.component';
import { PeriodeFormComponent } from './entities/periode/periode-form/periode-form.component';

// Postebudgetaire Components
import { PostebudgetaireListheaderComponent } from './entities/postebudgetaire/postebudgetaire-list/postebudgetaire-listheader.component';
import { PostebudgetaireListComponent } from './entities/postebudgetaire/postebudgetaire-list/postebudgetaire-list.component';
import { PostebudgetaireFormComponent } from './entities/postebudgetaire/postebudgetaire-form/postebudgetaire-form.component';

// Reliquat Components
import { ReliquatListheaderComponent } from './entities/reliquat/reliquat-list/reliquat-listheader.component';
import { ReliquatListComponent } from './entities/reliquat/reliquat-list/reliquat-list.component';
import { ReliquatFormComponent } from './entities/reliquat/reliquat-form/reliquat-form.component';

// Rubrique Components
import { RubriqueListheaderComponent } from './entities/rubrique/rubrique-list/rubrique-listheader.component';
import { RubriqueListComponent } from './entities/rubrique/rubrique-list/rubrique-list.component';
import { RubriqueFormComponent } from './entities/rubrique/rubrique-form/rubrique-form.component';

// Rubriquefrais Components
import { RubriquefraisListheaderComponent } from './entities/rubriquefrais/rubriquefrais-list/rubriquefrais-listheader.component';
import { RubriquefraisListComponent } from './entities/rubriquefrais/rubriquefrais-list/rubriquefrais-list.component';
import { RubriquefraisFormComponent } from './entities/rubriquefrais/rubriquefrais-form/rubriquefrais-form.component';

// Valocontrat Components
import { ValocontratListheaderComponent } from './entities/valocontrat/valocontrat-list/valocontrat-listheader.component';
import { ValocontratListComponent } from './entities/valocontrat/valocontrat-list/valocontrat-list.component';
import { ValocontratFormComponent } from './entities/valocontrat/valocontrat-form/valocontrat-form.component';

// Other Components
import { NotFoundComponent } from './not-found/not-found.component';
import { AboutComponent } from './about/about.component';
import { DeleteDialogComponent } from './delete-dialog/delete-dialog.component';
import { HomeListComponent } from './home-list/home-list.component';

// Modules
import { SimpleNotificationsModule } from 'angular2-notifications';
import {MatDatepickerModule} from '@angular/material/datepicker';

import { MaterialModule} from './material-module'
import { PrimengModule}  from './primeng-module'

// Services
import { AlerteService } from './entities/alerte/services/alerte.service';
import { BaremekmService } from './entities/baremekm/services/baremekm.service';
import { CalendrierService } from './entities/calendrier/services/calendrier.service';
import { ClientService } from './entities/client/services/client.service';
import { CongeService } from './entities/conge/services/conge.service';
import { ConsultantService } from './entities/consultant/services/consultant.service';
import { ConsultantcontratService } from './entities/consultantcontrat/services/consultantcontrat.service';
import { ConsultantcontratfournisseurService } from './entities/consultantcontratfournisseur/services/consultantcontratfournisseur.service';
import { ContratService } from './entities/contrat/services/contrat.service';
import { ContratfournisseurService } from './entities/contratfournisseur/services/contratfournisseur.service';
import { CraService } from './entities/cra/services/cra.service';
import { DocumentService } from './entities/document/services/document.service';
import { EcheancecontratService } from './entities/echeancecontrat/services/echeancecontrat.service';
import { EcheancecontratfournisseurService } from './entities/echeancecontratfournisseur/services/echeancecontratfournisseur.service';
import { ExerciceService } from './entities/exercice/services/exercice.service';
import { FournisseurService } from './entities/fournisseur/services/fournisseur.service';
import { FraisService } from './entities/frais/services/frais.service';
import { FraiskmunitService } from './entities/fraiskmunit/services/fraiskmunit.service';
import { FraisunitService } from './entities/fraisunit/services/fraisunit.service';
import { LiencontratService } from './entities/liencontrat/services/liencontrat.service';
import { ListeService } from './entities/liste/services/liste.service';
import { MenuService } from './entities/menu/services/menu.service';
import { PeriodeService } from './entities/periode/services/periode.service';
import { PostebudgetaireService } from './entities/postebudgetaire/services/postebudgetaire.service';
import { ReliquatService } from './entities/reliquat/services/reliquat.service';
import { RubriqueService } from './entities/rubrique/services/rubrique.service';
import { RubriquefraisService } from './entities/rubriquefrais/services/rubriquefrais.service';
import { ValocontratService } from './entities/valocontrat/services/valocontrat.service';
import { EmitterService } from './services/emitter.service';
import { NotificationService } from './services/notification.service';
// import { PagerService } from './services/pager.service';


import { ApplicationStateService } from './services/application-state.service';

import {AngularHalModule} from 'angular4-hal';
import {ExternalConfigurationService} from './ExternalConfigurationService';

//import { DatePipe } from '@angular/common';
import { DateAdapter, MAT_DATE_LOCALE } from '@angular/material/core';
import { MatMomentDateModule, MAT_MOMENT_DATE_ADAPTER_OPTIONS } from '@angular/material-moment-adapter';
// import { PickDateAdapter, PICK_FORMATS } from './adapter/pickdate.adapter';
import { PlatformModule} from '@angular/cdk/platform';

import { registerLocaleData } from '@angular/common';
import localeFr from '@angular/common/locales/fr';
import localeFrExtra from '@angular/common/locales/extra/fr';
// import TranslateModule from  '@ngx-translate/core';

import { AuthGuard } from './auth.guard';
import { LoginComponent } from './login/login.component';
import { LoginRoutingModule } from './login/login.routing';

import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { AngularDateHttpInterceptor } from './interceptors/AngularDateHttp.interceptor';

import {WebStorageModule, LocalStorageService} from "angular-localstorage";

import {FlexLayoutModule} from '@angular/flex-layout';
// import {NgbModule} from '@ng-bootstrap/ng-bootstrap';

// import { ScrollPanelModule } from 'primeng/scrollpanel';
// import { ButtonModule } from 'primeng/button';

registerLocaleData(localeFr, 'fr-FR', localeFrExtra);

@NgModule({
  declarations: [
    AppComponent,
	 AppMenuComponent,
     AppSubMenuComponent,
     AppTopBarComponent,
     AppFooterComponent,
     DashboardComponent,

    AlerteListheaderComponent,
    AlerteListComponent,
    AlerteFormComponent,
    BaremekmListheaderComponent,
    BaremekmListComponent,
    BaremekmFormComponent,
    CalendrierListheaderComponent,
    CalendrierListComponent,
    CalendrierFormComponent,
    ClientListheaderComponent,
    ClientListComponent,
    ClientFormComponent,
    CongeListheaderComponent,
    CongeListComponent,
    CongeFormComponent,
    ConsultantListheaderComponent,
    ConsultantListComponent,
    ConsultantFormComponent,
    ConsultantcontratListheaderComponent,
    ConsultantcontratListComponent,
    ConsultantcontratFormComponent,
    ConsultantcontratfournisseurListheaderComponent,
    ConsultantcontratfournisseurListComponent,
    ConsultantcontratfournisseurFormComponent,
    ContratListheaderComponent,
    ContratListComponent,
    ContratFormComponent,
    ContratfournisseurListheaderComponent,
    ContratfournisseurListComponent,
    ContratfournisseurFormComponent,
    CraListheaderComponent,
    CraListComponent,
    CraFormComponent,
    DocumentListheaderComponent,
    DocumentListComponent,
    DocumentFormComponent,
    EcheancecontratListheaderComponent,
    EcheancecontratListComponent,
    EcheancecontratFormComponent,
    EcheancecontratfournisseurListheaderComponent,
    EcheancecontratfournisseurListComponent,
    EcheancecontratfournisseurFormComponent,
    ExerciceListheaderComponent,
    ExerciceListComponent,
    ExerciceFormComponent,
    FournisseurListheaderComponent,
    FournisseurListComponent,
    FournisseurFormComponent,
    FraisListheaderComponent,
    FraisListComponent,
    FraisFormComponent,
    FraiskmunitListheaderComponent,
    FraiskmunitListComponent,
    FraiskmunitFormComponent,
    FraisunitListheaderComponent,
    FraisunitListComponent,
    FraisunitFormComponent,
    LiencontratListheaderComponent,
    LiencontratListComponent,
    LiencontratFormComponent,
    ListeListheaderComponent,
    ListeListComponent,
    ListeFormComponent,
    MenuListheaderComponent,
    MenuListComponent,
    MenuFormComponent,
    PeriodeListheaderComponent,
    PeriodeListComponent,
    PeriodeFormComponent,
    PostebudgetaireListheaderComponent,
    PostebudgetaireListComponent,
    PostebudgetaireFormComponent,
    ReliquatListheaderComponent,
    ReliquatListComponent,
    ReliquatFormComponent,
    RubriqueListheaderComponent,
    RubriqueListComponent,
    RubriqueFormComponent,
    RubriquefraisListheaderComponent,
    RubriquefraisListComponent,
    RubriquefraisFormComponent,
    ValocontratListheaderComponent,
    ValocontratListComponent,
    ValocontratFormComponent,
    NotFoundComponent,
    AboutComponent,
    DeleteDialogComponent,
    HomeListComponent,
    LoginComponent
],
  entryComponents: [
    DeleteDialogComponent
],
  imports: [
    BrowserModule,
    CommonModule,
    ReactiveFormsModule,
    HttpClientModule,
    LoginRoutingModule, // doit être avant AppRouting
    AppRouting,
    BrowserAnimationsModule,
	MaterialModule,
    MatDatepickerModule,
    PlatformModule,
    SimpleNotificationsModule.forRoot(),
    AngularHalModule.forRoot(),
    MatMomentDateModule, // permet de gérer la timezone
    FlexLayoutModule,
	PrimengModule, // PrimeNg
    //ScrollPanelModule,
    //ButtonModule	
	//AppMenuModule,
    //AppTopBarModule,
    //AppFooterModule,
],
  providers: [
    { provide: 'ExternalConfigurationService', useClass: ExternalConfigurationService },
    { provide: MAT_DATE_LOCALE, useValue: 'fr-FR' },
    { provide: MAT_MOMENT_DATE_ADAPTER_OPTIONS, useValue: { useUtc: true } },
    AlerteService,
    BaremekmService,
    CalendrierService,
    ClientService,
    CongeService,
    ConsultantService,
    ConsultantcontratService,
    ConsultantcontratfournisseurService,
    ContratService,
    ContratfournisseurService,
    CraService,
    DocumentService,
    EcheancecontratService,
    EcheancecontratfournisseurService,
    ExerciceService,
    FournisseurService,
    FraisService,
    FraiskmunitService,
    FraisunitService,
    LiencontratService,
    ListeService,
    MenuService,
    PeriodeService,
    PostebudgetaireService,
    ReliquatService,
    RubriqueService,
    RubriquefraisService,
    ValocontratService,
    EmitterService,
    NotificationService,
	ApplicationStateService,
    MatDatepickerModule,
    AuthGuard,
    {
      provide: HTTP_INTERCEPTORS,
      useClass: AngularDateHttpInterceptor,
      multi: true
    },
    // LocalStorageService
    // DatePipe
],
  bootstrap: [AppComponent]
})
export class AppModule {
     constructor(private dateAdapter: DateAdapter<Date>){
       dateAdapter.setLocale('fr-FR');
   }
 }
