// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-20 ( Time 13:26:40 )

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { CommonModule } from '@angular/common';

import { ReactiveFormsModule } from '@angular/forms';

import { AppComponent } from './app.component';
// Routing
import { AppRouting } from './app.routing';

import { HttpClientModule } from '@angular/common/http';

import { AppMenuComponent, AppSubMenuComponent} from './app.menu.component';
import { AppTopBarComponent } from './app.topbar.component';
import { AppFooterComponent } from './app.footer.component';
import { DashboardComponent } from './pages/dashboard.component';


// Calendrier Components
import { CalendrierListheaderComponent } from './entities/calendrier/calendrier-list/calendrier-listheader.component';
import { CalendrierListComponent } from './entities/calendrier/calendrier-list/calendrier-list.component';
import { CalendrierFormComponent } from './entities/calendrier/calendrier-form/calendrier-form.component';

// Consultant Components
import { ConsultantListheaderComponent } from './entities/consultant/consultant-list/consultant-listheader.component';
import { ConsultantListComponent } from './entities/consultant/consultant-list/consultant-list.component';
import { ConsultantFormComponent } from './entities/consultant/consultant-form/consultant-form.component';

// Fournisseur Components
import { FournisseurListheaderComponent } from './entities/fournisseur/fournisseur-list/fournisseur-listheader.component';
import { FournisseurListComponent } from './entities/fournisseur/fournisseur-list/fournisseur-list.component';
import { FournisseurFormComponent } from './entities/fournisseur/fournisseur-form/fournisseur-form.component';

// Liste Components
import { ListeListheaderComponent } from './entities/liste/liste-list/liste-listheader.component';
import { ListeListComponent } from './entities/liste/liste-list/liste-list.component';
import { ListeFormComponent } from './entities/liste/liste-form/liste-form.component';

// Menu Components
import { MenuListheaderComponent } from './entities/menu/menu-list/menu-listheader.component';
import { MenuListComponent } from './entities/menu/menu-list/menu-list.component';
import { MenuFormComponent } from './entities/menu/menu-form/menu-form.component';

// Periode Components
import { PeriodeListheaderComponent } from './entities/periode/periode-list/periode-listheader.component';
import { PeriodeListComponent } from './entities/periode/periode-list/periode-list.component';
import { PeriodeFormComponent } from './entities/periode/periode-form/periode-form.component';

// Exercice Components
import { ExerciceListheaderComponent } from './entities/exercice/exercice-list/exercice-listheader.component';
import { ExerciceListComponent } from './entities/exercice/exercice-list/exercice-list.component';
import { ExerciceFormComponent } from './entities/exercice/exercice-form/exercice-form.component';

// Other Components
import { NotFoundComponent } from './not-found/not-found.component';
import { AboutComponent } from './about/about.component';
import { DeleteDialogComponent } from './delete-dialog/delete-dialog.component';
import { HomeListComponent } from './home-list/home-list.component';

// Modules
import { SimpleNotificationsModule } from 'angular2-notifications';
import {MatDatepickerModule} from '@angular/material/datepicker';

import { MaterialModule} from './material-module'
import { PrimengModule}  from './primeng-module'

// Services
import { CalendrierService } from './entities/calendrier/services/calendrier.service';
import { ConsultantService } from './entities/consultant/services/consultant.service';
import { FournisseurService } from './entities/fournisseur/services/fournisseur.service';
import { ListeService } from './entities/liste/services/liste.service';
import { MenuService } from './entities/menu/services/menu.service';
import { PeriodeService } from './entities/periode/services/periode.service';
import { ExerciceService } from './entities/exercice/services/exercice.service';


import { EmitterService } from './services/emitter.service';
import { NotificationService } from './services/notification.service';
// import { PagerService } from './services/pager.service';


import { ApplicationStateService } from './services/application-state.service';

import {AngularHalModule} from 'angular4-hal';
import {ExternalConfigurationService} from './ExternalConfigurationService';

//import { DatePipe } from '@angular/common';
import { DateAdapter, MAT_DATE_LOCALE } from '@angular/material/core';
import { MatMomentDateModule, MAT_MOMENT_DATE_ADAPTER_OPTIONS } from '@angular/material-moment-adapter';
// import { PickDateAdapter, PICK_FORMATS } from './adapter/pickdate.adapter';
import { PlatformModule} from '@angular/cdk/platform';

import { registerLocaleData } from '@angular/common';
import localeFr from '@angular/common/locales/fr';
import localeFrExtra from '@angular/common/locales/extra/fr';
// import TranslateModule from  '@ngx-translate/core';

import { AuthGuard } from './auth.guard';
import { LoginComponent } from './login/login.component';
import { LoginRoutingModule } from './login/login.routing';

import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { AngularDateHttpInterceptor } from './interceptors/AngularDateHttp.interceptor';

import {WebStorageModule, LocalStorageService} from "angular-localstorage";

import {FlexLayoutModule} from '@angular/flex-layout';
// import {NgbModule} from '@ng-bootstrap/ng-bootstrap';

// import { ScrollPanelModule } from 'primeng/scrollpanel';
// import { ButtonModule } from 'primeng/button';

registerLocaleData(localeFr, 'fr-FR', localeFrExtra);

@NgModule({
  declarations: [
    AppComponent,
	 AppMenuComponent,
     AppSubMenuComponent,
     AppTopBarComponent,
     AppFooterComponent,
     DashboardComponent,

    CalendrierListheaderComponent,
    CalendrierListComponent,
    CalendrierFormComponent,
    ConsultantListheaderComponent,
    ConsultantListComponent,
    ConsultantFormComponent,
    FournisseurListheaderComponent,
    FournisseurListComponent,
    FournisseurFormComponent,
    ListeListheaderComponent,
    ListeListComponent,
    ListeFormComponent,
    MenuListheaderComponent,
    MenuListComponent,
    MenuFormComponent,
    PeriodeListheaderComponent,
    PeriodeListComponent,
    PeriodeFormComponent,
    ExerciceListheaderComponent,
    ExerciceListComponent,
    ExerciceFormComponent,

    NotFoundComponent,
    AboutComponent,
    DeleteDialogComponent,
    HomeListComponent,
    LoginComponent
],
  entryComponents: [
    DeleteDialogComponent
],
  imports: [
    BrowserModule,
    CommonModule,
    ReactiveFormsModule,
    HttpClientModule,
    LoginRoutingModule, // doit �tre avant AppRouting
    AppRouting,
    BrowserAnimationsModule,
	MaterialModule,
    MatDatepickerModule,
    PlatformModule,
    SimpleNotificationsModule.forRoot(),
    AngularHalModule.forRoot(),
    MatMomentDateModule, // permet de g�rer la timezone
    FlexLayoutModule,
	PrimengModule, // PrimeNg
    //ScrollPanelModule,
    //ButtonModule	
	//AppMenuModule,
    //AppTopBarModule,
    //AppFooterModule,
],
  providers: [
    { provide: 'ExternalConfigurationService', useClass: ExternalConfigurationService },
    { provide: MAT_DATE_LOCALE, useValue: 'fr-FR' },
    { provide: MAT_MOMENT_DATE_ADAPTER_OPTIONS, useValue: { useUtc: true } },
    CalendrierService,
    ConsultantService,
    FournisseurService,
    ListeService,
    MenuService,
    PeriodeService,
	ExerciceService,
    EmitterService,
    NotificationService,
	ApplicationStateService,
    MatDatepickerModule,
    AuthGuard,
    {
      provide: HTTP_INTERCEPTORS,
      useClass: AngularDateHttpInterceptor,
      multi: true
    },
    // LocalStorageService
    // DatePipe
],
  bootstrap: [AppComponent]
})
export class AppModule {
     constructor(private dateAdapter: DateAdapter<Date>){
       dateAdapter.setLocale('fr-FR');
   }
 }
