// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:28 )


import { Resource } from 'angular4-hal';

export class Fraiskmunit extends Resource {
	fraiskmunitid: number; // Wrapper Type : Number
	idconsultant: number; // Wrapper Type : Number
	codeperiode: string; // Wrapper Type : String
	datecalendrier: Date; // Wrapper Type : Date
	idcontrat: number; // Wrapper Type : Number
	nbkm: number; // Wrapper Type : Number
	commentaire: string; // Wrapper Type : String
	tauxkm: number; // Wrapper Type : Number
}
