// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:38 )


import { Resource } from 'angular4-hal';

export class Periode extends Resource {
	code: string; // Wrapper Type : String
	nom: string; // Wrapper Type : String
	codeexercice: string; // Wrapper Type : String
	ouvert: boolean; // Wrapper Type : Boolean
	actif: boolean; // Wrapper Type : Boolean
}
