// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-14 ( Time 19:52:59 )


import { Resource } from 'angular4-hal';

export class Periode extends Resource {
	code: string; // Wrapper Type : String
	nom: string; // Wrapper Type : String
	codeexercice: string; // Wrapper Type : String
	ouvert: string; // Wrapper Type : String
	actif: string; // Wrapper Type : String
}
