// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 16:11:31 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-cra-listheader',
  templateUrl: './cra-listheader.component.html',
  styleUrls: ['./cra-listheader.component.css'],
  providers: []
})
export class CraListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Cras';
  public filter:string = 'FULL';

  private columnDefinitions = [
      { def: 'codeperiode', showMobile: true },
      { def: 'idconsultant', showMobile: true },
      { def: 'statut', showMobile: true },
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
