// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:23 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';
import { Router } from '@angular/router';
import { ActivatedRoute  } from '@angular/router';
import { MatDialog } from '@angular/material';

// Services imports
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { CraService } from './../services/cra.service';
import { ApplicationStateService } from './../../../services/application-state.service';

// Models imports
import { Cra } from '../cra.model';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Ajout primeng
import {TableModule} from 'primeng/table';
import {PaginatorModule} from 'primeng/paginator';

@Component({
  selector: 'app-cra-list',
  templateUrl: './cra-list.component.html',
  styleUrls: ['./cra-list.component.css'],
  providers: [DatePipe]
})
export class CraListComponent implements OnInit, OnChanges {

  public title = 'Liste de Cras';

  public listOfCras: Cra[];


  _filter : string;
  @Input('filter') 
  set filter(value:string) {
	 this._filter = value;
     this.getAllCras();
  }

  get filter():string {
	return this._filter
  }

  @Input() createenable?: boolean = true;
  @Input() deleteenable?: boolean = true;
  @Input() updateenable?: boolean = true;
  @Input() incard?: boolean = true;

  private listId = 'CRA_COMPONENT_LIST';

  private cra: Cra;

  private columnDefinitions = [
      { def: 'craid', showMobile: true, display:'none', index:0},
      { def: 'commentaire', showMobile: true, display:'none', index:1},
      { def: 'DATEVALIDATION', showMobile: true, display:'none', index:2},
      { def: 'codeperiode', showMobile: true, display:'table-cell', index:3},
      { def: 'idconsultant', showMobile: true, display:'table-cell', index:4},
      { def: 'statut', showMobile: true, display:'table-cell', index:5},
	];

  constructor(
    private _craService: CraService,
    private _router: Router,
    private _notificationService: NotificationService,
    public dialog: MatDialog,
	private _route: ActivatedRoute) { }

  ngOnInit() {
    // On init get all Cras
    //this.getAllCras();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Cra list
    EmitterService.get(this.listId).subscribe((data: Cra[]) => this.getAllCras());
  }

  ngOnChanges() { }


  /**
   * Get displayed columns (responsive)
   */
  getDisplayedColumns(): string[] {
	  const isMobile = ApplicationStateService.getIsMobileResolution();
	  return this.columnDefinitions
	    .filter(cd => !isMobile || cd.showMobile)
	    .map(cd => cd.def);
	}

  /**
   * Get all Cra using the service CraService
   */
  getAllCras = (): void => {

	var options:any = { notPaged: true };
	
	if (this.filter) {
		if (this.filter == 'FULL') {
			options = { notPaged: true };
		}
		else {
			var filters = JSON.parse(this.filter);
			options = {params: filters,
						   notPaged: true};
		}

    	this._craService.getAll(options).subscribe(
      		(data: Cra[]) => {
        		this.listOfCras = data;
      		},
      	error => {
        	this._notificationService.error(
          	'Error',
          	'An error occured when trying to reach the server');
    	});
	}
  }

  editCra = (craid): void => {
    // Navigate to cra form component
    this.goToCraForm(craid);
  }

  deleteCra = (craid): void => {

    const promise = new Promise((resolve, reject) => {
		// Call get service
		this._craService.get(craid).subscribe(
        		(cra: Cra) => {
          							this.cra = cra;
          							resolve('done');
        						},
				error => {
          					this._notificationService.error(error.statusText, 'Error delete');
            				reject('error');
        				 });
	})
    .then(() => {
    	// Call delete service
    	this._craService.delete(this.cra).subscribe(
      			result => {
       						 // Notify Cra list to refresh
        					EmitterService.get(this.listId).emit(result);

        					this._notificationService.success(
          					'Deleted',
          					`The cra entry with the id='${craid}' was deleted successfuly`);
     					  },
      			error => {
        					this._notificationService.error(
          					'Error',
          					'An error occured when trying to reach the server');
      					  });
  	})
  }

  goToCraForm(craid) {
    this._router.navigate(['./cra-form', craid]);
  }

  deleteConfirmation = (craid) => {
    const dialogRef = this.dialog.open(DeleteDialogComponent, {
      data: `cra: ${craid}`
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteCra(craid);
      }
    });
  }

}
