// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:20 )

// Modules imports
import { NotificationService } from './../../../services/notification.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material';
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Models and services imports
import { Consultantcontratfournisseur } from './../consultantcontratfournisseur.model';
import { ConsultantcontratfournisseurService } from './../services/consultantcontratfournisseur.service';
import * as _ from 'underscore';

// Pour gestion des listes
import { ListeService } from './../../../entities/liste/services/liste.service';
import { Liste } from './../../../entities/liste/liste.model';

import { Lov } from './../../../common/lov';
import {SelectItem} from 'primeng/api';

@Component({
  selector: 'app-consultantcontratfournisseur-form',
  templateUrl: './consultantcontratfournisseur-form.component.html',
  styleUrls: ['./consultantcontratfournisseur-form.component.css'],
  providers: [DatePipe]
})
export class ConsultantcontratfournisseurFormComponent extends Lov implements OnInit {

  // HTTP status code
  readonly NOT_FOUND_ERROR = 404;
  readonly CONFLICT_ERROR = 409;
  readonly INTERNAL_SERVER_ERROR = 500;

  public title = 'Formulaire Consultantcontratfournisseur';
  public form: FormGroup;

  // Définition des filtres

  public consultantcontratfournisseur: Consultantcontratfournisseur;
  private ids;

  // Définition des LOV

  constructor(
	private _listeService: ListeService,         // Pour gestion des listes
    private _consultantcontratfournisseurService: ConsultantcontratfournisseurService,
    private _route: ActivatedRoute,
    private _router: Router,
    private _formBuilder: FormBuilder,
    private _notificationService: NotificationService,
    public dialog: MatDialog) {
		super(_listeService,_notificationService);
 	}

  ngOnInit() {
    this.getIdFromRouteParams();
    this.initForm();
  }

  getIdFromRouteParams = () => {
    this._route.params.subscribe(p => {
        this.ids = _.values(p);
    });
  }

  initForm = () => {
    this.form = this._formBuilder.group(this.getNewForm());
    if (!_.isEmpty(this.ids)) {
      this.load();
    }

	/* Chargement des LOVs */
  }

  getNewForm = (consultantcontratfournisseur?: Consultantcontratfournisseur) => {
    return {
      idconsultant: [
          (consultantcontratfournisseur ? consultantcontratfournisseur.idconsultant : ''),
          Validators.required
      ],
      idcontratfournisseur: [
          (consultantcontratfournisseur ? consultantcontratfournisseur.idcontratfournisseur : ''),
          Validators.required
      ],
      datedebut: [
        (consultantcontratfournisseur ? consultantcontratfournisseur.datedebut : null)
      ],
      datefin: [
        (consultantcontratfournisseur ? consultantcontratfournisseur.datefin : null)
      ],
      taux: [
        (consultantcontratfournisseur ? consultantcontratfournisseur.taux : ''),
        Validators.required
      ],
      nbjprev: [
        (consultantcontratfournisseur ? consultantcontratfournisseur.nbjprev : ''),
        Validators.required
      ],
      profilcst: [
        (consultantcontratfournisseur ? consultantcontratfournisseur.profilcst : ''),
        Validators.required
      ]
    };
  }


  load = () => {
	// Concaténer les ids mais séparé par / et non ,
	var param : String = '';
	
	for (var i=0;i<this.ids.length;i++) {
		param = param + this.ids[i];
		if (i != (this.ids.length-1)) {
			param = param + '/';
		}
	}
    this._consultantcontratfournisseurService.get(param).subscribe(
      (consultantcontratfournisseur: Consultantcontratfournisseur) => {
        this.consultantcontratfournisseur = consultantcontratfournisseur;
        this.form = this._formBuilder.group(this.getNewForm(this.consultantcontratfournisseur));
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
 	  },
      () => {
		// Valorisation des filtres
      });
  }

  save = () => {
	// If we didn't get a consultantcontratfournisseur, we are adding a consultantcontratfournisseur
    if (!this.consultantcontratfournisseur) {
      this.add();
    } else { // If we didn't get a consultantcontratfournisseur, we are adding a consultantcontratfournisseur
      this.update();
    }
  }

  add = () => {
    this._consultantcontratfournisseurService.create(this.form.value).subscribe(
      result => {
        this._notificationService.success('Success', 'Consultantcontratfournisseur added successfuly');
        this._router.navigate(['./consultantcontratfournisseur-form', this.form.value.idconsultant, this.form.value.idcontratfournisseur]);
      },
      error => {1
        if (error.status === this.CONFLICT_ERROR) {
          this._notificationService.error(error.statusText, 'Id already used in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  update = () => {
	Object.assign(this.consultantcontratfournisseur,this.form.value);
    this._consultantcontratfournisseurService.update(this.consultantcontratfournisseur).subscribe(
      result => this._notificationService.success('Success', 'Consultantcontratfournisseur edited successfuly'),
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  deleteConfirmation = () => {
    if (this.consultantcontratfournisseur.idconsultant && this.consultantcontratfournisseur.idcontratfournisseur) {
      const dialogRef = this.dialog.open(DeleteDialogComponent, {
        data: `consultantcontratfournisseur: ${this.consultantcontratfournisseur.idconsultant}, ${this.consultantcontratfournisseur.idcontratfournisseur}`
      });
      dialogRef.afterClosed().subscribe(result => {
        if (result) {
          this.deleteBadge(this.consultantcontratfournisseur);
        }
      });
    }
  }

  deleteBadge = (consultantcontratfournisseur: Consultantcontratfournisseur): void => {
    // Call delete service
    this._consultantcontratfournisseurService.delete(consultantcontratfournisseur).subscribe(
      result => {
        this._router.navigate(['./consultantcontratfournisseur-list']);

        this._notificationService.success(
          'Deleted',
         // `The consultantcontratfournisseur entry with the id(s)='${idconsultant}, ${idcontratfournisseur}' was deleted successfuly`);
 		`The consultantcontratfournisseur entry with the id= was deleted successfuly`);
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }
}
