// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:29 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Fraisunit } from '../fraisunit.model';

@Injectable()
export class FraisunitService extends RestService<Fraisunit>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Fraisunit, 'fraisunit', injector);
    }

}
