// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:33 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Postebudgetaire } from '../postebudgetaire.model';

@Injectable()
export class PostebudgetaireService extends RestService<Postebudgetaire>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Postebudgetaire, 'postebudgetaire', injector);
    }

}
