// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:31 )


import { Resource } from 'angular4-hal';

export class Frais extends Resource {
	fraisid: number; // Wrapper Type : Number
	idconsultant: number; // Wrapper Type : Number
	codeperiode: string; // Wrapper Type : String
	commentaire: string; // Wrapper Type : String
	statut: string; // Wrapper Type : String
	datevalidation: Date; // Wrapper Type : Date
	datepaiement: Date; // Wrapper Type : Date
	paiement: boolean; // Wrapper Type : Boolean
}
