// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:34 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Reliquat } from '../reliquat.model';

@Injectable()
export class ReliquatService extends RestService<Reliquat>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Reliquat, 'reliquat', injector);
    }

}
