// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:22 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-conge-listheader',
  templateUrl: './conge-listheader.component.html',
  styleUrls: ['./conge-listheader.component.css'],
  providers: []
})
export class CongeListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Conges';
  public filter:string = 'FULL';

  private columnDefinitions = [
      { def: 'congeid', showMobile: true },
      { def: 'idconsultant', showMobile: true },
      { def: 'codeexercice', showMobile: true },
      { def: 'datedebut', showMobile: true },
      { def: 'datefin', showMobile: true },
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
