// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:24 )

// Modules imports
import { NotificationService } from './../../../services/notification.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material';
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Models and services imports
import { Consultantcontrat } from './../consultantcontrat.model';
import { ConsultantcontratService } from './../services/consultantcontrat.service';
import * as _ from 'underscore';

// Pour gestion des listes
import { ListeService } from './../../../entities/liste/services/liste.service';
import { Liste } from './../../../entities/liste/liste.model';

import { Lov } from './../../../common/lov';
import {SelectItem} from 'primeng/api';

@Component({
  selector: 'app-consultantcontrat-form',
  templateUrl: './consultantcontrat-form.component.html',
  styleUrls: ['./consultantcontrat-form.component.css'],
  providers: [DatePipe]
})
export class ConsultantcontratFormComponent extends Lov implements OnInit {

  // HTTP status code
  readonly NOT_FOUND_ERROR = 404;
  readonly CONFLICT_ERROR = 409;
  readonly INTERNAL_SERVER_ERROR = 500;

  public title = 'Formulaire Consultantcontrat';
  public form: FormGroup;

  // Définition des filtres

  public consultantcontrat: Consultantcontrat;
  private ids;

  // Définition des LOV

  constructor(
	private _listeService: ListeService,         // Pour gestion des listes
    private _consultantcontratService: ConsultantcontratService,
    private _route: ActivatedRoute,
    private _router: Router,
    private _formBuilder: FormBuilder,
    private _notificationService: NotificationService,
    public dialog: MatDialog) {
		super(_listeService,_notificationService);
 	}

  ngOnInit() {
    this.getIdFromRouteParams();
    this.initForm();
  }

  getIdFromRouteParams = () => {
    this._route.params.subscribe(p => {
        this.ids = _.values(p);
    });
  }

  initForm = () => {
    this.form = this._formBuilder.group(this.getNewForm());
    if (!_.isEmpty(this.ids)) {
      this.load();
    }

	/* Chargement des LOVs */
  }

  getNewForm = (consultantcontrat?: Consultantcontrat) => {
    return {
      idconsultant: [
          (consultantcontrat ? consultantcontrat.idconsultant : ''),
          Validators.required
      ],
      idcontrat: [
          (consultantcontrat ? consultantcontrat.idcontrat : ''),
          Validators.required
      ],
      datedebut: [
        (consultantcontrat ? consultantcontrat.datedebut : null)
      ],
      datefin: [
        (consultantcontrat ? consultantcontrat.datefin : null)
      ],
      taux: [
        (consultantcontrat ? consultantcontrat.taux : ''),
        Validators.required
      ],
      nbjprev: [
        (consultantcontrat ? consultantcontrat.nbjprev : ''),
        Validators.required
      ],
      fraisrefact: [
        (consultantcontrat ? consultantcontrat.fraisrefact : '')
      ],
      fraisforfait: [
        (consultantcontrat ? consultantcontrat.fraisforfait : '')
      ],
      fraisforfaitmnt: [
        (consultantcontrat ? consultantcontrat.fraisforfaitmnt : '')
      ],
      fraiskmqte: [
        (consultantcontrat ? consultantcontrat.fraiskmqte : '')
      ],
      fraistype: [
        (consultantcontrat ? consultantcontrat.fraistype : '')
      ],
      profilcst: [
        (consultantcontrat ? consultantcontrat.profilcst : ''),
        Validators.required
      ]
    };
  }


  load = () => {
	// Concaténer les ids mais séparé par / et non ,
	var param : String = '';
	
	for (var i=0;i<this.ids.length;i++) {
		param = param + this.ids[i];
		if (i != (this.ids.length-1)) {
			param = param + '/';
		}
	}
    this._consultantcontratService.get(param).subscribe(
      (consultantcontrat: Consultantcontrat) => {
        this.consultantcontrat = consultantcontrat;
        this.form = this._formBuilder.group(this.getNewForm(this.consultantcontrat));
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
 	  },
      () => {
		// Valorisation des filtres
      });
  }

  save = () => {
	// If we didn't get a consultantcontrat, we are adding a consultantcontrat
    if (!this.consultantcontrat) {
      this.add();
    } else { // If we didn't get a consultantcontrat, we are adding a consultantcontrat
      this.update();
    }
  }

  add = () => {
    this._consultantcontratService.create(this.form.value).subscribe(
      result => {
        this._notificationService.success('Success', 'Consultantcontrat added successfuly');
        this._router.navigate(['./consultantcontrat-form', this.form.value.idconsultant, this.form.value.idcontrat]);
      },
      error => {1
        if (error.status === this.CONFLICT_ERROR) {
          this._notificationService.error(error.statusText, 'Id already used in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  update = () => {
	Object.assign(this.consultantcontrat,this.form.value);
    this._consultantcontratService.update(this.consultantcontrat).subscribe(
      result => this._notificationService.success('Success', 'Consultantcontrat edited successfuly'),
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  deleteConfirmation = () => {
    if (this.consultantcontrat.idconsultant && this.consultantcontrat.idcontrat) {
      const dialogRef = this.dialog.open(DeleteDialogComponent, {
        data: `consultantcontrat: ${this.consultantcontrat.idconsultant}, ${this.consultantcontrat.idcontrat}`
      });
      dialogRef.afterClosed().subscribe(result => {
        if (result) {
          this.deleteBadge(this.consultantcontrat);
        }
      });
    }
  }

  deleteBadge = (consultantcontrat: Consultantcontrat): void => {
    // Call delete service
    this._consultantcontratService.delete(consultantcontrat).subscribe(
      result => {
        this._router.navigate(['./consultantcontrat-list']);

        this._notificationService.success(
          'Deleted',
         // `The consultantcontrat entry with the id(s)='${idconsultant}, ${idcontrat}' was deleted successfuly`);
 		`The consultantcontrat entry with the id= was deleted successfuly`);
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }
}
