// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-15 ( Time 08:51:33 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-calendrier-listheader',
  templateUrl: './calendrier-listheader.component.html',
  styleUrls: ['./calendrier-listheader.component.css'],
  providers: []
})
export class CalendrierListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Calendriers';
  public filter:string = 'FULL';

  constructor(
) {
	
 }

  ngOnInit() { }

  ngOnChanges() { }

}
