// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-23 ( Time 15:26:34 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';
import { Router } from '@angular/router';
import { ActivatedRoute  } from '@angular/router';
import { MatDialog } from '@angular/material';

// Services imports
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { CalendrierService } from './../services/calendrier.service';
import { ApplicationStateService } from './../../../services/application-state.service';

// Models imports
import { Calendrier } from '../calendrier.model';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Ajout primeng
import {TableModule} from 'primeng/table';
import {PaginatorModule} from 'primeng/paginator';

@Component({
  selector: 'app-calendrier-list',
  templateUrl: './calendrier-list.component.html',
  styleUrls: ['./calendrier-list.component.css'],
  providers: [DatePipe]
})
export class CalendrierListComponent implements OnInit, OnChanges {

  public title = 'Liste de Calendriers';

  public listOfCalendriers: Calendrier[];


  _filter : string;
  @Input('filter') 
  set filter(value:string) {
	 this._filter = value;
     this.getAllCalendriers();
  }

  get filter():string {
	return this._filter
  }

  @Input() createenable?: boolean = true;
  @Input() deleteenable?: boolean = true;
  @Input() updateenable?: boolean = true;
  @Input() incard?: boolean = true;

  private listId = 'CALENDRIER_COMPONENT_LIST';

  private calendrier: Calendrier;

  private columnDefinitions = [
      { def: 'codeperiode', showMobile: true },
      { def: 'datecalendrier', showMobile: true },
      { def: 'ferie', showMobile: true },
	];

  constructor(
    private _calendrierService: CalendrierService,
    private _router: Router,
    private _notificationService: NotificationService,
    public dialog: MatDialog,
	private _route: ActivatedRoute) { }

  ngOnInit() {
    // On init get all Calendriers
    //this.getAllCalendriers();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Calendrier list
    EmitterService.get(this.listId).subscribe((data: Calendrier[]) => this.getAllCalendriers());
  }

  ngOnChanges() { }


  /**
   * Get displayed columns (responsive)
   */
  getDisplayedColumns(): string[] {
	  const isMobile = ApplicationStateService.getIsMobileResolution();
	  return this.columnDefinitions
	    .filter(cd => !isMobile || cd.showMobile)
	    .map(cd => cd.def);
	}

  /**
   * Get all Calendrier using the service CalendrierService
   */
  getAllCalendriers = (): void => {

	var options:any = { notPaged: true };
	
	if (this.filter) {
		if (this.filter == 'FULL') {
			options = { notPaged: true };
		}
		else {
			var filters = JSON.parse(this.filter);
			options = {params: filters,
						   notPaged: true};
		}

    	this._calendrierService.getAll(options).subscribe(
      		(data: Calendrier[]) => {
        		this.listOfCalendriers = data;
      		},
      	error => {
        	this._notificationService.error(
          	'Error',
          	'An error occured when trying to reach the server');
    	});
	}
  }

  editCalendrier = (datecalendrier): void => {
    // Navigate to calendrier form component
    this.goToCalendrierForm(datecalendrier);
  }

  deleteCalendrier = (datecalendrier): void => {

    const promise = new Promise((resolve, reject) => {
		// Call get service
		this._calendrierService.get(datecalendrier).subscribe(
        		(calendrier: Calendrier) => {
          							this.calendrier = calendrier;
          							resolve('done');
        						},
				error => {
          					this._notificationService.error(error.statusText, 'Error delete');
            				reject('error');
        				 });
	})
    .then(() => {
    	// Call delete service
    	this._calendrierService.delete(this.calendrier).subscribe(
      			result => {
       						 // Notify Calendrier list to refresh
        					EmitterService.get(this.listId).emit(result);

        					this._notificationService.success(
          					'Deleted',
          					`The calendrier entry with the id='${datecalendrier}' was deleted successfuly`);
     					  },
      			error => {
        					this._notificationService.error(
          					'Error',
          					'An error occured when trying to reach the server');
      					  });
  	})
  }

  goToCalendrierForm(datecalendrier) {
    this._router.navigate(['./calendrier-form', datecalendrier.toISOString()]);
  }

  deleteConfirmation = (datecalendrier) => {
    const dialogRef = this.dialog.open(DeleteDialogComponent, {
      data: `calendrier: ${datecalendrier}`
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteCalendrier(datecalendrier);
      }
    });
  }

}
