// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:29 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Exercice } from '../exercice.model';

@Injectable()
export class ExerciceService extends RestService<Exercice>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Exercice, 'exercice', injector);
    }

}
