// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:28 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Echeancecontrat } from '../echeancecontrat.model';

@Injectable()
export class EcheancecontratService extends RestService<Echeancecontrat>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Echeancecontrat, 'echeancecontrat', injector);
    }

}
