// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 15:13:44 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';
import { Router } from '@angular/router';
import { ActivatedRoute  } from '@angular/router';
import { MatDialog } from '@angular/material';

// Services imports
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { ValocontratService } from './../services/valocontrat.service';
import { ApplicationStateService } from './../../../services/application-state.service';

// Models imports
import { Valocontrat } from '../valocontrat.model';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Ajout primeng
import {TableModule} from 'primeng/table';
import {PaginatorModule} from 'primeng/paginator';

@Component({
  selector: 'app-valocontrat-list',
  templateUrl: './valocontrat-list.component.html',
  styleUrls: ['./valocontrat-list.component.css'],
  providers: [DatePipe]
})
export class ValocontratListComponent implements OnInit, OnChanges {

  public title = 'Liste de Valocontrats';

  public listOfValocontrats: Valocontrat[];


  _filter : string;
  @Input('filter') 
  set filter(value:string) {
	 this._filter = value;
     this.getAllValocontrats();
  }

  get filter():string {
	return this._filter
  }

  @Input() createenable?: boolean = true;
  @Input() deleteenable?: boolean = true;
  @Input() updateenable?: boolean = true;
  @Input() incard?: boolean = true;

  private listId = 'VALOCONTRAT_COMPONENT_LIST';

  private valocontrat: Valocontrat;

  private columnDefinitions = [
      { def: 'valocontratid', showMobile: true, display:'none', index:0},
      { def: 'idcontrat', showMobile: true, display:'table-cell', index:1},
      { def: 'profilcst', showMobile: true, display:'table-cell', index:2},
      { def: 'libelle', showMobile: true, display:'table-cell', index:3},
      { def: 'nbj', showMobile: true, display:'table-cell', index:4},
      { def: 'taux', showMobile: true, display:'table-cell', index:5},
	];

  constructor(
    private _valocontratService: ValocontratService,
    private _router: Router,
    private _notificationService: NotificationService,
    public dialog: MatDialog,
	private _route: ActivatedRoute) { }

  ngOnInit() {
    // On init get all Valocontrats
    //this.getAllValocontrats();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Valocontrat list
    EmitterService.get(this.listId).subscribe((data: Valocontrat[]) => this.getAllValocontrats());
  }

  ngOnChanges() { }


  /**
   * Get displayed columns (responsive)
   */
  getDisplayedColumns(): string[] {
	  const isMobile = ApplicationStateService.getIsMobileResolution();
	  return this.columnDefinitions
	    .filter(cd => !isMobile || cd.showMobile)
	    .map(cd => cd.def);
	}

  /**
   * Get all Valocontrat using the service ValocontratService
   */
  getAllValocontrats = (): void => {

	var options:any = { notPaged: true };
	
	if (this.filter) {
		if (this.filter == 'FULL') {
			options = { notPaged: true };
		}
		else {
			var filters = JSON.parse(this.filter);
			options = {params: filters,
						   notPaged: true};
		}

    	this._valocontratService.getAll(options).subscribe(
      		(data: Valocontrat[]) => {
        		this.listOfValocontrats = data;
      		},
      	error => {
        	this._notificationService.error(
          	'Error',
          	'An error occured when trying to reach the server');
    	});
	}
  }

  editValocontrat = (valocontratid): void => {
    // Navigate to valocontrat form component
    this.goToValocontratForm(valocontratid);
  }

  deleteValocontrat = (valocontratid): void => {

    const promise = new Promise((resolve, reject) => {
		// Call get service
		this._valocontratService.get([valocontratid]).subscribe(
        		(valocontrat: Valocontrat) => {
          							this.valocontrat = valocontrat;
          							resolve('done');
        						},
				error => {
          					this._notificationService.error(error.statusText, 'Error delete');
            				reject('error');
        				 });
	})
    .then(() => {
    	// Call delete service
    	this._valocontratService.delete(this.valocontrat).subscribe(
      			result => {
       						 // Notify Valocontrat list to refresh
        					EmitterService.get(this.listId).emit(result);

        					this._notificationService.success(
          					'Deleted',
          					`The valocontrat entry with the id='${valocontratid}' was deleted successfuly`);
     					  },
      			error => {
        					this._notificationService.error(
          					'Error',
          					'An error occured when trying to reach the server');
      					  });
  	})
  }

  goToValocontratForm(valocontratid) {
    this._router.navigate(['./valocontrat-form', valocontratid]);
  }

  deleteConfirmation = (valocontratid) => {
    const dialogRef = this.dialog.open(DeleteDialogComponent, {
      data: `valocontrat: ${valocontratid}`
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteValocontrat(valocontratid);
      }
    });
  }

}
