// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:37 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-valocontrat-listheader',
  templateUrl: './valocontrat-listheader.component.html',
  styleUrls: ['./valocontrat-listheader.component.css'],
  providers: []
})
export class ValocontratListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Valocontrats';
  public filter:string = 'FULL';

  private columnDefinitions = [
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
