// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 15:13:44 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-valocontrat-listheader',
  templateUrl: './valocontrat-listheader.component.html',
  styleUrls: ['./valocontrat-listheader.component.css'],
  providers: []
})
export class ValocontratListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Valocontrats';
  public filter:string = 'FULL';

  private columnDefinitions = [
      { def: 'idcontrat', showMobile: true },
      { def: 'profilcst', showMobile: true },
      { def: 'libelle', showMobile: true },
      { def: 'nbj', showMobile: true },
      { def: 'taux', showMobile: true },
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
