// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:20 )


import { Resource } from 'angular4-hal';

export class Consultantcontratfournisseur extends Resource {
	idconsultant: number; // Wrapper Type : Number
	idcontratfournisseur: number; // Wrapper Type : Number
	datedebut: Date; // Wrapper Type : Date
	datefin: Date; // Wrapper Type : Date
	taux: number; // Wrapper Type : Number
	nbjprev: number; // Wrapper Type : Number
	profilcst: string; // Wrapper Type : String
}
