// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-02-07 ( Time 17:22:11 )


import { Resource } from 'angular4-hal';

export class Menu extends Resource {
	codemenu: string; // Wrapper Type : String
	url: string; // Wrapper Type : String
	image: string; // Wrapper Type : String
	nom: string; // Wrapper Type : String
	profils: string; // Wrapper Type : String
}
