// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:31 )


import { Resource } from 'angular4-hal';

export class Menu extends Resource {
	codemenu: string; // Wrapper Type : String
	url: string; // Wrapper Type : String
	image: string; // Wrapper Type : String
	nom: string; // Wrapper Type : String
	profils: string; // Wrapper Type : String
}
