// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 16:11:43 )

// Modules imports
import { NotificationService } from './../../../services/notification.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material';
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Models and services imports
import { Reliquat } from './../reliquat.model';
import { ReliquatService } from './../services/reliquat.service';
import * as _ from 'underscore';

// Pour gestion des listes
import { ListeService } from './../../../entities/liste/services/liste.service';
import { Liste } from './../../../entities/liste/liste.model';

import { Lov } from './../../../common/lov';
import {SelectItem} from 'primeng/api';

@Component({
  selector: 'app-reliquat-form',
  templateUrl: './reliquat-form.component.html',
  styleUrls: ['./reliquat-form.component.css'],
  providers: [DatePipe]
})
export class ReliquatFormComponent extends Lov implements OnInit {

  // HTTP status code
  readonly NOT_FOUND_ERROR = 404;
  readonly CONFLICT_ERROR = 409;
  readonly INTERNAL_SERVER_ERROR = 500;

  public title = 'Formulaire Reliquat';
  public form: FormGroup;

  // Définition des filtres

  public reliquat: Reliquat;
  private ids;

  // Définition des LOV

  constructor(
	private _listeService: ListeService,         // Pour gestion des listes
    private _reliquatService: ReliquatService,
    private _route: ActivatedRoute,
    private _router: Router,
    private _formBuilder: FormBuilder,
    private _notificationService: NotificationService,
    public dialog: MatDialog) {
		super(_listeService,_notificationService);
 	}

  ngOnInit() {
    this.getIdFromRouteParams();
    this.initForm();
  }

  getIdFromRouteParams = () => {
    this._route.params.subscribe(p => {
        this.ids = _.values(p);
    });
  }

  initForm = () => {
    this.form = this._formBuilder.group(this.getNewForm());
    if (!_.isEmpty(this.ids)) {
      this.load();
    }

	/* Chargement des LOVs */
  }

  getNewForm = (reliquat?: Reliquat) => {
    return {
      codeexercice: [
          (reliquat ? reliquat.codeexercice : ''),
          Validators.required
      ],
      idconsultant: [
          (reliquat ? reliquat.idconsultant : ''),
          Validators.required
      ],
      codetypeactivite: [
          (reliquat ? reliquat.codetypeactivite : ''),
          Validators.required
      ],
      quantite: [
        (reliquat ? reliquat.quantite : '')
      ],
      comment: [
        (reliquat ? reliquat.comment : '')
      ]
    };
  }


  load = () => {
	// Concaténer les ids mais séparé par / et non ,
	var param : String = '';
	
	for (var i=0;i<this.ids.length;i++) {
		param = param + this.ids[i];
		if (i != (this.ids.length-1)) {
			param = param + '/';
		}
	}
    this._reliquatService.get(param).subscribe(
      (reliquat: Reliquat) => {
        this.reliquat = reliquat;
        this.form = this._formBuilder.group(this.getNewForm(this.reliquat));
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
 	  },
      () => {
		// Valorisation des filtres
      });
  }

  save = () => {
	// If we didn't get a reliquat, we are adding a reliquat
    if (!this.reliquat) {
      this.add();
    } else { // If we didn't get a reliquat, we are adding a reliquat
      this.update();
    }
  }

  add = () => {
    this._reliquatService.create(this.form.value).subscribe(
      result => {
        this._notificationService.success('Success', 'Reliquat added successfuly');
        this._router.navigate(['./reliquat-form', this.form.value.codeexercice, this.form.value.idconsultant, this.form.value.codetypeactivite]);
      },
      error => {1
        if (error.status === this.CONFLICT_ERROR) {
          this._notificationService.error(error.statusText, 'Id already used in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  update = () => {
	Object.assign(this.reliquat,this.form.value);
    this._reliquatService.update(this.reliquat).subscribe(
      result => this._notificationService.success('Success', 'Reliquat edited successfuly'),
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  deleteConfirmation = () => {
    if (this.reliquat.codeexercice && this.reliquat.idconsultant && this.reliquat.codetypeactivite) {
      const dialogRef = this.dialog.open(DeleteDialogComponent, {
        data: `reliquat: ${this.reliquat.codeexercice}, ${this.reliquat.idconsultant}, ${this.reliquat.codetypeactivite}`
      });
      dialogRef.afterClosed().subscribe(result => {
        if (result) {
          this.deleteBadge(this.reliquat);
        }
      });
    }
  }

  deleteBadge = (reliquat: Reliquat): void => {
    // Call delete service
    this._reliquatService.delete(reliquat).subscribe(
      result => {
        this._router.navigate(['./reliquat-list']);

        this._notificationService.success(
          'Deleted',
         // `The reliquat entry with the id(s)='${codeexercice}, ${idconsultant}, ${codetypeactivite}' was deleted successfuly`);
 		`The reliquat entry with the id= was deleted successfuly`);
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }
}
