// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:21 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';
import { Router } from '@angular/router';
import { ActivatedRoute  } from '@angular/router';
import { MatDialog } from '@angular/material';

// Services imports
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { ContratService } from './../services/contrat.service';
import { ApplicationStateService } from './../../../services/application-state.service';

// Models imports
import { Contrat } from '../contrat.model';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Ajout primeng
import {TableModule} from 'primeng/table';
import {PaginatorModule} from 'primeng/paginator';

@Component({
  selector: 'app-contrat-list',
  templateUrl: './contrat-list.component.html',
  styleUrls: ['./contrat-list.component.css'],
  providers: [DatePipe]
})
export class ContratListComponent implements OnInit, OnChanges {

  public title = 'Liste de Contrats';

  public listOfContrats: Contrat[];


  _filter : string;
  @Input('filter') 
  set filter(value:string) {
	 this._filter = value;
     this.getAllContrats();
  }

  get filter():string {
	return this._filter
  }

  @Input() createenable?: boolean = true;
  @Input() deleteenable?: boolean = true;
  @Input() updateenable?: boolean = true;
  @Input() incard?: boolean = true;

  private listId = 'CONTRAT_COMPONENT_LIST';

  private contrat: Contrat;

  private columnDefinitions = [
      { def: 'idclientsec', showMobile: true, display:'none', index:0},
      { def: 'contact1', showMobile: true, display:'none', index:1},
      { def: 'tel1_portable', showMobile: true, display:'none', index:2},
      { def: 'tel1_travail', showMobile: true, display:'none', index:3},
      { def: 'tel1_domicile', showMobile: true, display:'none', index:4},
      { def: 'datedebut', showMobile: true, display:'none', index:5},
      { def: 'datefin', showMobile: true, display:'none', index:6},
      { def: 'referenceclient', showMobile: true, display:'none', index:7},
      { def: 'type', showMobile: true, display:'none', index:8},
      { def: 'etat_comm', showMobile: true, display:'none', index:9},
      { def: 'signature', showMobile: true, display:'none', index:10},
      { def: 'avancement', showMobile: true, display:'none', index:11},
      { def: 'nbj_prev', showMobile: true, display:'none', index:12},
      { def: 'adressefact', showMobile: true, display:'none', index:13},
      { def: 'contactfact', showMobile: true, display:'none', index:14},
      { def: 'avenant', showMobile: true, display:'none', index:15},
      { def: 'categorie', showMobile: true, display:'none', index:16},
      { def: 'mail1', showMobile: true, display:'none', index:17},
      { def: 'factcra', showMobile: true, display:'none', index:18},
      { def: 'datereception', showMobile: true, display:'none', index:19},
      { def: 'daterenvoi', showMobile: true, display:'none', index:20},
      { def: 'dateretour', showMobile: true, display:'none', index:21},
      { def: 'contratid', showMobile: true, display:'none', index:22},
      { def: 'reference', showMobile: true, display:'none', index:23},
      { def: 'idclient', showMobile: true, display:'none', index:24},
      { def: 'idclientsec', showMobile: true, display:'none', index:25},
      { def: 'contact1', showMobile: true, display:'none', index:26},
      { def: 'tel1_portable', showMobile: true, display:'none', index:27},
      { def: 'tel1_travail', showMobile: true, display:'none', index:28},
      { def: 'tel1_domicile', showMobile: true, display:'none', index:29},
      { def: 'datedebut', showMobile: true, display:'none', index:30},
      { def: 'datefin', showMobile: true, display:'none', index:31},
      { def: 'referenceclient', showMobile: true, display:'none', index:32},
      { def: 'type', showMobile: true, display:'none', index:33},
      { def: 'etat_comm', showMobile: true, display:'none', index:34},
      { def: 'signature', showMobile: true, display:'none', index:35},
      { def: 'avancement', showMobile: true, display:'none', index:36},
      { def: 'nbj_prev', showMobile: true, display:'none', index:37},
      { def: 'adressefact', showMobile: true, display:'none', index:38},
      { def: 'contactfact', showMobile: true, display:'none', index:39},
      { def: 'avenant', showMobile: true, display:'none', index:40},
      { def: 'categorie', showMobile: true, display:'none', index:41},
      { def: 'mail1', showMobile: true, display:'none', index:42},
      { def: 'factcra', showMobile: true, display:'none', index:43},
      { def: 'datereception', showMobile: true, display:'none', index:44},
      { def: 'daterenvoi', showMobile: true, display:'none', index:45},
      { def: 'dateretour', showMobile: true, display:'none', index:46},
      { def: 'contratid', showMobile: true, display:'table-cell', index:47},
      { def: 'reference', showMobile: true, display:'table-cell', index:48},
      { def: 'idclient', showMobile: true, display:'table-cell', index:49},
	];

  constructor(
    private _contratService: ContratService,
    private _router: Router,
    private _notificationService: NotificationService,
    public dialog: MatDialog,
	private _route: ActivatedRoute) { }

  ngOnInit() {
    // On init get all Contrats
    //this.getAllContrats();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Contrat list
    EmitterService.get(this.listId).subscribe((data: Contrat[]) => this.getAllContrats());
  }

  ngOnChanges() { }


  /**
   * Get displayed columns (responsive)
   */
  getDisplayedColumns(): string[] {
	  const isMobile = ApplicationStateService.getIsMobileResolution();
	  return this.columnDefinitions
	    .filter(cd => !isMobile || cd.showMobile)
	    .map(cd => cd.def);
	}

  /**
   * Get all Contrat using the service ContratService
   */
  getAllContrats = (): void => {

	var options:any = { notPaged: true };
	
	if (this.filter) {
		if (this.filter == 'FULL') {
			options = { notPaged: true };
		}
		else {
			var filters = JSON.parse(this.filter);
			options = {params: filters,
						   notPaged: true};
		}

    	this._contratService.getAll(options).subscribe(
      		(data: Contrat[]) => {
        		this.listOfContrats = data;
      		},
      	error => {
        	this._notificationService.error(
          	'Error',
          	'An error occured when trying to reach the server');
    	});
	}
  }

  editContrat = (contratid): void => {
    // Navigate to contrat form component
    this.goToContratForm(contratid);
  }

  deleteContrat = (contratid): void => {

    const promise = new Promise((resolve, reject) => {
		// Call get service
		this._contratService.get(contratid).subscribe(
        		(contrat: Contrat) => {
          							this.contrat = contrat;
          							resolve('done');
        						},
				error => {
          					this._notificationService.error(error.statusText, 'Error delete');
            				reject('error');
        				 });
	})
    .then(() => {
    	// Call delete service
    	this._contratService.delete(this.contrat).subscribe(
      			result => {
       						 // Notify Contrat list to refresh
        					EmitterService.get(this.listId).emit(result);

        					this._notificationService.success(
          					'Deleted',
          					`The contrat entry with the id='${contratid}' was deleted successfuly`);
     					  },
      			error => {
        					this._notificationService.error(
          					'Error',
          					'An error occured when trying to reach the server');
      					  });
  	})
  }

  goToContratForm(contratid) {
    this._router.navigate(['./contrat-form', contratid]);
  }

  deleteConfirmation = (contratid) => {
    const dialogRef = this.dialog.open(DeleteDialogComponent, {
      data: `contrat: ${contratid}`
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteContrat(contratid);
      }
    });
  }

}
