// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 16:11:39 )

// Modules imports
import { NotificationService } from './../../../services/notification.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material';
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Models and services imports
import { Liencontrat } from './../liencontrat.model';
import { LiencontratService } from './../services/liencontrat.service';
import * as _ from 'underscore';

// Pour gestion des listes
import { ListeService } from './../../../entities/liste/services/liste.service';
import { Liste } from './../../../entities/liste/liste.model';

import { Lov } from './../../../common/lov';
import {SelectItem} from 'primeng/api';

@Component({
  selector: 'app-liencontrat-form',
  templateUrl: './liencontrat-form.component.html',
  styleUrls: ['./liencontrat-form.component.css'],
  providers: [DatePipe]
})
export class LiencontratFormComponent extends Lov implements OnInit {

  // HTTP status code
  readonly NOT_FOUND_ERROR = 404;
  readonly CONFLICT_ERROR = 409;
  readonly INTERNAL_SERVER_ERROR = 500;

  public title = 'Formulaire Liencontrat';
  public form: FormGroup;

  // Définition des filtres

  public liencontrat: Liencontrat;
  private ids;

  // Définition des LOV

  constructor(
	private _listeService: ListeService,         // Pour gestion des listes
    private _liencontratService: LiencontratService,
    private _route: ActivatedRoute,
    private _router: Router,
    private _formBuilder: FormBuilder,
    private _notificationService: NotificationService,
    public dialog: MatDialog) {
		super(_listeService,_notificationService);
 	}

  ngOnInit() {
    this.getIdFromRouteParams();
    this.initForm();
  }

  getIdFromRouteParams = () => {
    this._route.params.subscribe(p => {
        this.ids = _.values(p);
    });
  }

  initForm = () => {
    this.form = this._formBuilder.group(this.getNewForm());
    if (!_.isEmpty(this.ids)) {
      this.load();
    }

	/* Chargement des LOVs */
  }

  getNewForm = (liencontrat?: Liencontrat) => {
    return {
      idcontratclient: [
          (liencontrat ? liencontrat.idcontratclient : ''),
          Validators.required
      ],
      idconsultantclient: [
          (liencontrat ? liencontrat.idconsultantclient : ''),
          Validators.required
      ],
      idcontratfournisseur: [
          (liencontrat ? liencontrat.idcontratfournisseur : ''),
          Validators.required
      ],
      idconsultantfournisseur: [{
        value: (liencontrat ? liencontrat.idconsultantfournisseur : ''),
        disabled: true
      }]
    };
  }


  load = () => {
	// Concaténer les ids mais séparé par / et non ,
	var param : String = '';
	
	for (var i=0;i<this.ids.length;i++) {
		param = param + this.ids[i];
		if (i != (this.ids.length-1)) {
			param = param + '/';
		}
	}
    this._liencontratService.get(param).subscribe(
      (liencontrat: Liencontrat) => {
        this.liencontrat = liencontrat;
        this.form = this._formBuilder.group(this.getNewForm(this.liencontrat));
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
 	  },
      () => {
		// Valorisation des filtres
      });
  }

  save = () => {
	// If we didn't get a liencontrat, we are adding a liencontrat
    if (!this.liencontrat) {
      this.add();
    } else { // If we didn't get a liencontrat, we are adding a liencontrat
      this.update();
    }
  }

  add = () => {
    this._liencontratService.create(this.form.value).subscribe(
      result => {
        this._notificationService.success('Success', 'Liencontrat added successfuly');
        this._router.navigate(['./liencontrat-form', this.form.value.idcontratclient, this.form.value.idconsultantclient, this.form.value.idcontratfournisseur, this.form.value.idconsultantfournisseur]);
      },
      error => {1
        if (error.status === this.CONFLICT_ERROR) {
          this._notificationService.error(error.statusText, 'Id already used in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  update = () => {
	Object.assign(this.liencontrat,this.form.value);
    this._liencontratService.update(this.liencontrat).subscribe(
      result => this._notificationService.success('Success', 'Liencontrat edited successfuly'),
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  deleteConfirmation = () => {
    if (this.liencontrat.idcontratclient && this.liencontrat.idconsultantclient && this.liencontrat.idcontratfournisseur && this.liencontrat.idconsultantfournisseur) {
      const dialogRef = this.dialog.open(DeleteDialogComponent, {
        data: `liencontrat: ${this.liencontrat.idcontratclient}, ${this.liencontrat.idconsultantclient}, ${this.liencontrat.idcontratfournisseur}, ${this.liencontrat.idconsultantfournisseur}`
      });
      dialogRef.afterClosed().subscribe(result => {
        if (result) {
          this.deleteBadge(this.liencontrat);
        }
      });
    }
  }

  deleteBadge = (liencontrat: Liencontrat): void => {
    // Call delete service
    this._liencontratService.delete(liencontrat).subscribe(
      result => {
        this._router.navigate(['./liencontrat-list']);

        this._notificationService.success(
          'Deleted',
         // `The liencontrat entry with the id(s)='${idcontratclient}, ${idconsultantclient}, ${idcontratfournisseur}, ${idconsultantfournisseur}' was deleted successfuly`);
 		`The liencontrat entry with the id= was deleted successfuly`);
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }
}
