// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:30 )


import { Resource } from 'angular4-hal';

export class Liste extends Resource {
	nomliste: string; // Wrapper Type : String
	codeelement: string; // Wrapper Type : String
	nomelement: string; // Wrapper Type : String
	ordretri: string; // Wrapper Type : String
	image: string; // Wrapper Type : String
	defaut: string; // Wrapper Type : String
}
