// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:40 )

import { RestService } from 'angular4-hal';
import { Injectable, Injector } from '@angular/core';
import { Profil } from '../profil.model';

@Injectable()
export class ProfilService extends RestService<Profil>  {

    /**
     * Constructor
     * @param _http Http
     * @param _configuration Configuration
     */
    constructor(injector: Injector) {
        super(Profil, 'profil', injector);
    }

}
