// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:33 )

// Modules imports
import { NotificationService } from './../../../services/notification.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material';
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit } from '@angular/core';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Models and services imports
import { Postebudgetaire } from './../postebudgetaire.model';
import { PostebudgetaireService } from './../services/postebudgetaire.service';
import * as _ from 'underscore';

// Pour gestion des listes
import { ListeService } from './../../../entities/liste/services/liste.service';
import { Liste } from './../../../entities/liste/liste.model';

import { Lov } from './../../../common/lov';
import {SelectItem} from 'primeng/api';

@Component({
  selector: 'app-postebudgetaire-form',
  templateUrl: './postebudgetaire-form.component.html',
  styleUrls: ['./postebudgetaire-form.component.css'],
  providers: [DatePipe]
})
export class PostebudgetaireFormComponent extends Lov implements OnInit {

  // HTTP status code
  readonly NOT_FOUND_ERROR = 404;
  readonly CONFLICT_ERROR = 409;
  readonly INTERNAL_SERVER_ERROR = 500;

  public title = 'Formulaire Postebudgetaire';
  public form: FormGroup;

  // Définition des filtres

  public postebudgetaire: Postebudgetaire;
  private ids;

  // Définition des LOV

  constructor(
	private _listeService: ListeService,         // Pour gestion des listes
    private _postebudgetaireService: PostebudgetaireService,
    private _route: ActivatedRoute,
    private _router: Router,
    private _formBuilder: FormBuilder,
    private _notificationService: NotificationService,
    public dialog: MatDialog) {
		super(_listeService,_notificationService);
 	}

  ngOnInit() {
    this.getIdFromRouteParams();
    this.initForm();
  }

  getIdFromRouteParams = () => {
    this._route.params.subscribe(p => {
        this.ids = _.values(p);
    });
  }

  initForm = () => {
    this.form = this._formBuilder.group(this.getNewForm());
    if (!_.isEmpty(this.ids)) {
      this.load();
    }

	/* Chargement des LOVs */
  }

  getNewForm = (postebudgetaire?: Postebudgetaire) => {
    return {
      code: [
          (postebudgetaire ? postebudgetaire.code : ''),
          Validators.required
      ],
      nom: [
        (postebudgetaire ? postebudgetaire.nom : '')
      ],
      ordre: [
        (postebudgetaire ? postebudgetaire.ordre : '')
      ],
      analytique: [
        (postebudgetaire ? postebudgetaire.analytique : '')
      ],
      image: [
        (postebudgetaire ? postebudgetaire.image : '')
      ]
    };
  }


  load = () => {
	// Concaténer les ids mais séparé par / et non ,
	var param : String = '';
	
	for (var i=0;i<this.ids.length;i++) {
		param = param + this.ids[i];
		if (i != (this.ids.length-1)) {
			param = param + '/';
		}
	}
    this._postebudgetaireService.get(param).subscribe(
      (postebudgetaire: Postebudgetaire) => {
        this.postebudgetaire = postebudgetaire;
        this.form = this._formBuilder.group(this.getNewForm(this.postebudgetaire));
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
 	  },
      () => {
		// Valorisation des filtres
      });
  }

  save = () => {
	// If we didn't get a postebudgetaire, we are adding a postebudgetaire
    if (!this.postebudgetaire) {
      this.add();
    } else { // If we didn't get a postebudgetaire, we are adding a postebudgetaire
      this.update();
    }
  }

  add = () => {
    this._postebudgetaireService.create(this.form.value).subscribe(
      result => {
        this._notificationService.success('Success', 'Postebudgetaire added successfuly');
        this._router.navigate(['./postebudgetaire-form', this.form.value.code]);
      },
      error => {1
        if (error.status === this.CONFLICT_ERROR) {
          this._notificationService.error(error.statusText, 'Id already used in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  update = () => {
	Object.assign(this.postebudgetaire,this.form.value);
    this._postebudgetaireService.update(this.postebudgetaire).subscribe(
      result => this._notificationService.success('Success', 'Postebudgetaire edited successfuly'),
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  deleteConfirmation = () => {
    if (this.postebudgetaire.code) {
      const dialogRef = this.dialog.open(DeleteDialogComponent, {
        data: `postebudgetaire: ${this.postebudgetaire.code}`
      });
      dialogRef.afterClosed().subscribe(result => {
        if (result) {
          this.deleteBadge(this.postebudgetaire);
        }
      });
    }
  }

  deleteBadge = (postebudgetaire: Postebudgetaire): void => {
    // Call delete service
    this._postebudgetaireService.delete(postebudgetaire).subscribe(
      result => {
        this._router.navigate(['./postebudgetaire-list']);

        this._notificationService.success(
          'Deleted',
         // `The postebudgetaire entry with the id(s)='${code}' was deleted successfuly`);
 		`The postebudgetaire entry with the id= was deleted successfuly`);
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }
}
