// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-27 ( Time 15:44:15 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';
import { Router } from '@angular/router';
import { ActivatedRoute  } from '@angular/router';
import { MatDialog } from '@angular/material';

// Services imports
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { AlerteService } from './../services/alerte.service';
import { ApplicationStateService } from './../../../services/application-state.service';

// Models imports
import { Alerte } from '../alerte.model';

// Components imports
import { DeleteDialogComponent } from './../../../delete-dialog/delete-dialog.component';

import { DatePipe } from '@angular/common';

// Ajout primeng
import {TableModule} from 'primeng/table';
import {PaginatorModule} from 'primeng/paginator';

@Component({
  selector: 'app-alerte-list',
  templateUrl: './alerte-list.component.html',
  styleUrls: ['./alerte-list.component.css'],
  providers: [DatePipe]
})
export class AlerteListComponent implements OnInit, OnChanges {

  public title = 'Liste de Alertes';

  public listOfAlertes: Alerte[];


  _filter : string;
  @Input('filter') 
  set filter(value:string) {
	 this._filter = value;
     this.getAllAlertes();
  }

  get filter():string {
	return this._filter
  }

  @Input() createenable?: boolean = true;
  @Input() deleteenable?: boolean = true;
  @Input() updateenable?: boolean = true;
  @Input() incard?: boolean = true;

  private listId = 'ALERTE_COMPONENT_LIST';

  private alerte: Alerte;

  private columnDefinitions = [
      { def: 'code', showMobile: true, display:'table-cell', index:0},
      { def: 'description', showMobile: true, display:'table-cell', index:1},
      { def: 'email', showMobile: true, display:'table-cell', index:2},
	];

  constructor(
    private _alerteService: AlerteService,
    private _router: Router,
    private _notificationService: NotificationService,
    public dialog: MatDialog,
	private _route: ActivatedRoute) { }

  ngOnInit() {
    // On init get all Alertes
    //this.getAllAlertes();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Alerte list
    EmitterService.get(this.listId).subscribe((data: Alerte[]) => this.getAllAlertes());
  }

  ngOnChanges() { }


  /**
   * Get displayed columns (responsive)
   */
  getDisplayedColumns(): string[] {
	  const isMobile = ApplicationStateService.getIsMobileResolution();
	  return this.columnDefinitions
	    .filter(cd => !isMobile || cd.showMobile)
	    .map(cd => cd.def);
	}

  /**
   * Get all Alerte using the service AlerteService
   */
  getAllAlertes = (): void => {

	var options:any = { notPaged: true };
	
	if (this.filter) {
		if (this.filter == 'FULL') {
			options = { notPaged: true };
		}
		else {
			var filters = JSON.parse(this.filter);
			options = {params: filters,
						   notPaged: true};
		}

    	this._alerteService.getAll(options).subscribe(
      		(data: Alerte[]) => {
        		this.listOfAlertes = data;
      		},
      	error => {
        	this._notificationService.error(
          	'Error',
          	'An error occured when trying to reach the server');
    	});
	}
  }

  editAlerte = (code): void => {
    // Navigate to alerte form component
    this.goToAlerteForm(code);
  }

  deleteAlerte = (code): void => {

    const promise = new Promise((resolve, reject) => {
		// Call get service
		this._alerteService.get(code).subscribe(
        		(alerte: Alerte) => {
          							this.alerte = alerte;
          							resolve('done');
        						},
				error => {
          					this._notificationService.error(error.statusText, 'Error delete');
            				reject('error');
        				 });
	})
    .then(() => {
    	// Call delete service
    	this._alerteService.delete(this.alerte).subscribe(
      			result => {
       						 // Notify Alerte list to refresh
        					EmitterService.get(this.listId).emit(result);

        					this._notificationService.success(
          					'Deleted',
          					`The alerte entry with the id='${code}' was deleted successfuly`);
     					  },
      			error => {
        					this._notificationService.error(
          					'Error',
          					'An error occured when trying to reach the server');
      					  });
  	})
  }

  goToAlerteForm(code) {
    this._router.navigate(['./alerte-form', code]);
  }

  deleteConfirmation = (code) => {
    const dialogRef = this.dialog.open(DeleteDialogComponent, {
      data: `alerte: ${code}`
    });
    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteAlerte(code);
      }
    });
  }

}
