// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 16:11:25 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-client-listheader',
  templateUrl: './client-listheader.component.html',
  styleUrls: ['./client-listheader.component.css'],
  providers: []
})
export class ClientListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Clients';
  public filter:string = 'FULL';

  private columnDefinitions = [
      { def: 'clientid', showMobile: true },
      { def: 'raisonsociale', showMobile: true },
      { def: 'contact1', showMobile: true },
      { def: 'tel1Portable', showMobile: true },
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
