// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:37 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-listeattr-listheader',
  templateUrl: './listeattr-listheader.component.html',
  styleUrls: ['./listeattr-listheader.component.css'],
  providers: []
})
export class ListeattrListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Listeattrs';
  public filter:string = 'FULL';

  private columnDefinitions = [
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
