// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 16:11:37 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-fraiskmunit-listheader',
  templateUrl: './fraiskmunit-listheader.component.html',
  styleUrls: ['./fraiskmunit-listheader.component.css'],
  providers: []
})
export class FraiskmunitListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Fraiskmunits';
  public filter:string = 'FULL';

  private columnDefinitions = [
      { def: 'fraiskmunitid', showMobile: true },
      { def: 'idconsultant', showMobile: true },
      { def: 'codeperiode', showMobile: true },
      { def: 'datecalendrier', showMobile: true },
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
