// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:33 )

// Modules imports
import { Component, OnInit, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-fraiskmunit-listheader',
  templateUrl: './fraiskmunit-listheader.component.html',
  styleUrls: ['./fraiskmunit-listheader.component.css'],
  providers: []
})
export class FraiskmunitListheaderComponent implements OnInit, OnChanges {

  public title = 'Liste de Fraiskmunits';
  public filter:string = 'FULL';

  private columnDefinitions = [
	];

  constructor() { }

  ngOnInit() { }

  ngOnChanges() { }
 
}
