// File generated by Telosys Tools Generator ( version 3.1.2 ) - Date 2020-04-28 ( Time 12:07:33 )


import { Resource } from 'angular4-hal';

export class Fraisunit extends Resource {
	fraisunitid: number; // Wrapper Type : Number
	idconsultant: number; // Wrapper Type : Number
	codeperiode: string; // Wrapper Type : String
	codetypefrais: string; // Wrapper Type : String
	datecalendrier: Date; // Wrapper Type : Date
	idcontrat: number; // Wrapper Type : Number
	montantht: number; // Wrapper Type : Number
	tva1: number; // Wrapper Type : Number
	tva2: number; // Wrapper Type : Number
	tva3: number; // Wrapper Type : Number
	recu: string; // Wrapper Type : String
	commentaire: string; // Wrapper Type : String
	refact: string; // Wrapper Type : String
}
